"""Auto-generated halal-safe mid-cap universe (2026-05-19)."""
MIDCAP_HALAL: dict[str, tuple[str, str]] = {
    'MKSI': ('Technology', 'Hardware, Equipment & Parts'),
    'NXT': ('Technology', 'Consumer Electronics'),
    'DD': ('Basic Materials', 'Chemicals - Specialty'),
    'ULS': ('Industrials', 'Specialty Business Services'),
    'WSM': ('Consumer Cyclical', 'Specialty Retail'),
    'EFX': ('Industrials', 'Consulting Services'),
    'RL': ('Consumer Cyclical', 'Apparel - Manufacturers'),
    'ENTG': ('Technology', 'Semiconductors'),
    'CF': ('Basic Materials', 'Agricultural Inputs'),
    'VTRS': ('Healthcare', 'Drug Manufacturers - Specialty & Generic'),
    'HPQ': ('Technology', 'Computer Hardware'),
    'RBA': ('Industrials', 'Specialty Business Services'),
    'SITM': ('Technology', 'Semiconductors'),
    'MRNA': ('Healthcare', 'Biotechnology'),
    'INCY': ('Healthcare', 'Biotechnology'),
    'EVRG': ('Utilities', 'Regulated Electric'),
    'SNA': ('Industrials', 'Manufacturing - Tools & Accessories'),
    'IFF': ('Basic Materials', 'Chemicals - Specialty'),
    'PKG': ('Consumer Cyclical', 'Packaging & Containers'),
    'LUV': ('Industrials', 'Airlines, Airports & Air Services'),
    'LNT': ('Utilities', 'Regulated Electric'),
    'WES': ('Energy', 'Oil & Gas Midstream'),
    'SMCI': ('Technology', 'Computer Hardware'),
    'IONQ': ('Technology', 'Computer Hardware'),
    'RS': ('Basic Materials', 'Steel'),
    'SNX': ('Technology', 'Technology Distributors'),
    'ROKU': ('Communication Services', 'Entertainment'),
    'APG': ('Industrials', 'Engineering & Construction'),
    'BURL': ('Consumer Cyclical', 'Apparel - Retail'),
    'USFD': ('Consumer Defensive', 'Food Distribution'),
    'WMG': ('Communication Services', 'Entertainment'),
    'FTV': ('Industrials', 'Industrial - Machinery'),
    'GIS': ('Consumer Defensive', 'Packaged Foods'),
    'DLTR': ('Consumer Defensive', 'Discount Stores'),
    'VNOM': ('Energy', 'Oil & Gas Midstream'),
    'IOT': ('Technology', 'Software - Infrastructure'),
    'DKS': ('Consumer Cyclical', 'Specialty Retail'),
    'LII': ('Industrials', 'Construction'),
    'ITT': ('Industrials', 'Industrial - Machinery'),
    'RBC': ('Industrials', 'Manufacturing - Tools & Accessories'),
    'BR': ('Technology', 'Information Technology Services'),
    'CHTR': ('Communication Services', 'Telecommunications Services'),
    'WCC': ('Industrials', 'Industrial - Distribution'),
    'LSCC': ('Technology', 'Semiconductors'),
    'OVV': ('Energy', 'Oil & Gas Exploration & Production'),
    'RIVN': ('Consumer Cyclical', 'Auto - Manufacturers'),
    'PTC': ('Technology', 'Software - Application'),
    'TSCO': ('Consumer Cyclical', 'Specialty Retail'),
    'THC': ('Healthcare', 'Medical - Care Facilities'),
    'NWS': ('Communication Services', 'Entertainment'),
    'AA': ('Basic Materials', 'Aluminum'),
    'TTMI': ('Technology', 'Hardware, Equipment & Parts'),
    'WY': ('Basic Materials', 'Paper, Lumber & Forest Products'),
    'ZBH': ('Healthcare', 'Medical - Devices'),
    'AMKR': ('Technology', 'Semiconductors'),
    'PAA': ('Energy', 'Oil & Gas Midstream'),
    'SSNC': ('Technology', 'Software - Application'),
    'H': ('Consumer Cyclical', 'Travel Lodging'),
    'IP': ('Consumer Cyclical', 'Packaging & Containers'),
    'CLH': ('Industrials', 'Waste Management'),
    'WSO': ('Industrials', 'Industrial - Distribution'),
    'NBIX': ('Healthcare', 'Biotechnology'),
    'RGLD': ('Basic Materials', 'Gold'),
    'LDOS': ('Technology', 'Information Technology Services'),
    'IEX': ('Industrials', 'Industrial - Machinery'),
    'NDSN': ('Industrials', 'Industrial - Machinery'),
    'DOCN': ('Technology', 'Software - Infrastructure'),
    'DTM': ('Energy', 'Oil & Gas Midstream'),
    'PFGC': ('Consumer Defensive', 'Food Distribution'),
    'SN': ('Consumer Cyclical', 'Furnishings, Fixtures & Appliances'),
    'MLI': ('Industrials', 'Manufacturing - Metal Fabrication'),
    'PR': ('Energy', 'Oil & Gas Exploration & Production'),
    'GNRC': ('Industrials', 'Industrial - Machinery'),
    'BALL': ('Consumer Cyclical', 'Packaging & Containers'),
    'TLN': ('Utilities', 'Independent Power Producers'),
    'NWSA': ('Communication Services', 'Entertainment'),
    'GEN': ('Technology', 'Software - Infrastructure'),
    'OKTA': ('Technology', 'Software - Infrastructure'),
    'TKO': ('Communication Services', 'Entertainment'),
    'LECO': ('Industrials', 'Manufacturing - Tools & Accessories'),
    'APA': ('Energy', 'Oil & Gas Exploration & Production'),
    'ARMK': ('Industrials', 'Specialty Business Services'),
    'AAOI': ('Technology', 'Semiconductors'),
    'COKE': ('Consumer Defensive', 'Beverages - Non-Alcoholic'),
    'TYL': ('Technology', 'Software - Application'),
    'CSL': ('Industrials', 'Construction'),
    'DECK': ('Consumer Cyclical', 'Apparel - Footwear & Accessories'),
    'J': ('Industrials', 'Engineering & Construction'),
    'RMBS': ('Technology', 'Semiconductors'),
    'CDW': ('Technology', 'Information Technology Services'),
    'HAS': ('Consumer Cyclical', 'Leisure'),
    'PINS': ('Communication Services', 'Internet Content & Information'),
    'TRU': ('Industrials', 'Consulting Services'),
    'MAS': ('Consumer Cyclical', 'Furnishings, Fixtures & Appliances'),
    'SOLV': ('Healthcare', 'Medical - Care Facilities'),
    'RBRK': ('Technology', 'Software - Infrastructure'),
    'TOST': ('Technology', 'Software - Infrastructure'),
    'SGI': ('Consumer Defensive', 'Household & Personal Products'),
    'IESC': ('Industrials', 'Engineering & Construction'),
    'SOLS': ('Basic Materials', 'Chemicals - Specialty'),
    'MOD': ('Consumer Cyclical', 'Auto - Parts'),
    'GPC': ('Consumer Cyclical', 'Specialty Retail'),
    'PEN': ('Healthcare', 'Medical - Devices'),
    'TRMB': ('Technology', 'Hardware, Equipment & Parts'),
    'DVA': ('Healthcare', 'Medical - Care Facilities'),
    'BBIO': ('Healthcare', 'Biotechnology'),
    'GH': ('Healthcare', 'Medical - Diagnostics & Research'),
    'BWA': ('Consumer Cyclical', 'Auto - Parts'),
    'DINO': ('Energy', 'Oil & Gas Refining & Marketing'),
    'ONTO': ('Technology', 'Semiconductors'),
    'GGG': ('Industrials', 'Industrial - Machinery'),
    'DY': ('Industrials', 'Engineering & Construction'),
    'NTNX': ('Technology', 'Software - Infrastructure'),
    'MKC': ('Consumer Defensive', 'Packaged Foods'),
    'RRX': ('Industrials', 'Industrial - Machinery'),
    'APC': ('Energy', 'Oil & Gas Refining & Marketing'),
    'EXEL': ('Healthcare', 'Biotechnology'),
    'RPM': ('Basic Materials', 'Chemicals - Specialty'),
    'SMMT': ('Healthcare', 'Biotechnology'),
    'NYT': ('Communication Services', 'Publishing'),
    'BJ': ('Consumer Defensive', 'Discount Stores'),
    'ZBRA': ('Technology', 'Communication Equipment'),
    'SMTC': ('Technology', 'Semiconductors'),
    'SAIA': ('Industrials', 'Trucking'),
    'QXO': ('Industrials', 'Industrial - Distribution'),
    'BBY': ('Consumer Cyclical', 'Specialty Retail'),
    'GDDY': ('Technology', 'Software - Infrastructure'),
    'PNW': ('Utilities', 'Regulated Electric'),
    'FIVE': ('Consumer Defensive', 'Discount Stores'),
    'SANM': ('Technology', 'Hardware, Equipment & Parts'),
    'MDGL': ('Healthcare', 'Biotechnology'),
    'TOL': ('Consumer Cyclical', 'Residential Construction'),
    'MEDP': ('Healthcare', 'Medical - Diagnostics & Research'),
    'AVY': ('Consumer Cyclical', 'Packaging & Containers'),
    'IONS': ('Healthcare', 'Biotechnology'),
    'COO': ('Healthcare', 'Medical - Instruments & Supplies'),
    'AR': ('Energy', 'Oil & Gas Exploration & Production'),
    'DT': ('Technology', 'Software - Application'),
    'FIG': ('Technology', 'Software - Application'),
    'AEIS': ('Industrials', 'Electrical Equipment & Parts'),
    'SWK': ('Industrials', 'Manufacturing - Tools & Accessories'),
    'WLK': ('Basic Materials', 'Chemicals - Specialty'),
    'AXSM': ('Healthcare', 'Biotechnology'),
    'U': ('Technology', 'Software - Application'),
    'GWRE': ('Technology', 'Software - Application'),
    'TXRH': ('Consumer Cyclical', 'Restaurants'),
    'VIAV': ('Technology', 'Communication Equipment'),
    'HL': ('Basic Materials', 'Silver'),
    'BLD': ('Industrials', 'Engineering & Construction'),
    'CDE': ('Basic Materials', 'Gold'),
    'ALGN': ('Healthcare', 'Medical - Devices'),
    'AIT': ('Industrials', 'Industrial - Distribution'),
    'KNX': ('Industrials', 'Trucking'),
    'VICR': ('Technology', 'Hardware, Equipment & Parts'),
    'CLX': ('Consumer Defensive', 'Household & Personal Products'),
    'HRL': ('Consumer Defensive', 'Packaged Foods'),
    'APLD': ('Technology', 'Information Technology Services'),
    'SJM': ('Consumer Defensive', 'Packaged Foods'),
    'LFUS': ('Technology', 'Hardware, Equipment & Parts'),
    'AAON': ('Industrials', 'Construction'),
    'CACI': ('Technology', 'Information Technology Services'),
    'BTSG': ('Healthcare', 'Medical - Healthcare Information Services'),
    'SCI': ('Consumer Cyclical', 'Personal Products & Services'),
    'CCK': ('Consumer Cyclical', 'Packaging & Containers'),
    'HUBS': ('Technology', 'Software - Application'),
    'RVTY': ('Healthcare', 'Medical - Diagnostics & Research'),
    'GMED': ('Healthcare', 'Medical - Devices'),
    'ARW': ('Technology', 'Technology Distributors'),
    'UHS': ('Healthcare', 'Medical - Care Facilities'),
    'AM': ('Energy', 'Oil & Gas Midstream'),
    'SWKS': ('Technology', 'Semiconductors'),
    'WTRG': ('Utilities', 'Regulated Water'),
    'PODD': ('Healthcare', 'Medical - Devices'),
    'FPS': ('Industrials', 'Electrical Equipment & Parts'),
    'WMS': ('Industrials', 'Construction'),
    'EHC': ('Healthcare', 'Medical - Care Facilities'),
    'GSAT': ('Communication Services', 'Telecommunications Services'),
    'PAG': ('Consumer Cyclical', 'Auto - Dealerships'),
    'TTD': ('Communication Services', 'Advertising Agencies'),
    'MUSA': ('Consumer Cyclical', 'Specialty Retail'),
    'ARWR': ('Healthcare', 'Biotechnology'),
    'IT': ('Industrials', 'Consulting Services'),
    'AES': ('Utilities', 'Independent Power Producers'),
    'ENSG': ('Healthcare', 'Medical - Care Facilities'),
    'CGNX': ('Technology', 'Hardware, Equipment & Parts'),
    'DPZ': ('Consumer Cyclical', 'Restaurants'),
    'OKLO': ('Utilities', 'Regulated Electric'),
    'JOBY': ('Industrials', 'Airlines, Airports & Air Services'),
    'SFD': ('Consumer Defensive', 'Agricultural Farm Products'),
    'MP': ('Basic Materials', 'Industrial Materials'),
    'LGN': ('Industrials', 'Engineering & Construction'),
    'WTS': ('Industrials', 'Industrial - Machinery'),
    'SPXC': ('Industrials', 'Industrial - Machinery'),
    'RRC': ('Energy', 'Oil & Gas Exploration & Production'),
    'ELAN': ('Healthcare', 'Drug Manufacturers - Specialty & Generic'),
    'GTLS': ('Industrials', 'Industrial - Machinery'),
    'JKHY': ('Technology', 'Information Technology Services'),
    'DAR': ('Consumer Defensive', 'Packaged Foods'),
    'CR': ('Industrials', 'Industrial - Machinery'),
    'GME': ('Consumer Cyclical', 'Specialty Retail'),
    'OGE': ('Utilities', 'Regulated Electric'),
    'BSY': ('Technology', 'Software - Application'),
    'VMI': ('Industrials', 'Conglomerates'),
    'POWL': ('Industrials', 'Electrical Equipment & Parts'),
    'ESI': ('Basic Materials', 'Chemicals - Specialty'),
    'VSAT': ('Technology', 'Communication Equipment'),
    'SUN': ('Energy', 'Oil & Gas Refining & Marketing'),
    'CART': ('Consumer Cyclical', 'Specialty Retail'),
    'MOH': ('Healthcare', 'Medical - Healthcare Plans'),
    'BMRN': ('Healthcare', 'Biotechnology'),
    'DCI': ('Industrials', 'Industrial - Machinery'),
    'DOCU': ('Technology', 'Software - Application'),
    'ALSN': ('Consumer Cyclical', 'Auto - Parts'),
    'UHAL': ('Industrials', 'Rental & Leasing Services'),
    'MASI': ('Healthcare', 'Medical - Devices'),
    'CYTK': ('Healthcare', 'Biotechnology'),
    'CAVA': ('Consumer Cyclical', 'Restaurants'),
    'AGX': ('Industrials', 'Engineering & Construction'),
    'ACM': ('Industrials', 'Engineering & Construction'),
    'BAX': ('Healthcare', 'Medical - Instruments & Supplies'),
    'FORM': ('Technology', 'Semiconductors'),
    'BROS': ('Consumer Cyclical', 'Restaurants'),
    'LLYVK': ('Communication Services', 'Entertainment'),
    'ZG': ('Communication Services', 'Internet Content & Information'),
    'OC': ('Industrials', 'Construction'),
    'BAH': ('Industrials', 'Consulting Services'),
    'R': ('Industrials', 'Rental & Leasing Services'),
    'CHWY': ('Consumer Cyclical', 'Specialty Retail'),
    'Z': ('Communication Services', 'Internet Content & Information'),
    'SIRI': ('Communication Services', 'Entertainment'),
    'TTC': ('Industrials', 'Manufacturing - Tools & Accessories'),
    'CNM': ('Industrials', 'Industrial - Distribution'),
    'NE': ('Energy', 'Oil & Gas Drilling'),
    'KRYS': ('Healthcare', 'Biotechnology'),
    'AYI': ('Industrials', 'Electrical Equipment & Parts'),
    'PRMB': ('Consumer Defensive', 'Beverages - Non-Alcoholic'),
    'MSGS': ('Communication Services', 'Entertainment'),
    'FLS': ('Industrials', 'Industrial - Machinery'),
    'CHRD': ('Energy', 'Oil & Gas Exploration & Production'),
    'HESM': ('Energy', 'Oil & Gas Midstream'),
    'MTCH': ('Communication Services', 'Internet Content & Information'),
    'GKOS': ('Healthcare', 'Medical - Devices'),
    'ACI': ('Consumer Defensive', 'Grocery Stores'),
    'SFM': ('Consumer Defensive', 'Grocery Stores'),
    'QRVO': ('Technology', 'Semiconductors'),
    'HSIC': ('Healthcare', 'Medical - Distribution'),
    'DDS': ('Consumer Cyclical', 'Department Stores'),
    'SAIL': ('Technology', 'Software - Infrastructure'),
    'ENS': ('Industrials', 'Electrical Equipment & Parts'),
    'LEVI': ('Consumer Cyclical', 'Apparel - Manufacturers'),
}
