"""Auto-generated MAX halal universe (mkt cap > 500M, top by mkt cap)."""
MIDCAP_HALAL: dict[str, tuple[str, str]] = {
    'NVDA': ('Technology', 'Semiconductors'),
    'GOOGL': ('Communication Services', 'Internet Content & Information'),
    'GOOG': ('Communication Services', 'Internet Content & Information'),
    'AAPL': ('Technology', 'Consumer Electronics'),
    'MSFT': ('Technology', 'Software - Infrastructure'),
    'AMZN': ('Consumer Cyclical', 'Specialty Retail'),
    'AVGO': ('Technology', 'Semiconductors'),
    'META': ('Communication Services', 'Internet Content & Information'),
    'TSLA': ('Consumer Cyclical', 'Auto - Manufacturers'),
    'WMT': ('Consumer Defensive', 'Discount Stores'),
    'LLY': ('Healthcare', 'Drug Manufacturers - General'),
    'MU': ('Technology', 'Semiconductors'),
    'AMD': ('Technology', 'Semiconductors'),
    'XOM': ('Energy', 'Oil & Gas Integrated'),
    'JNJ': ('Healthcare', 'Drug Manufacturers - General'),
    'INTC': ('Technology', 'Semiconductors'),
    'ORCL': ('Technology', 'Software - Infrastructure'),
    'COST': ('Consumer Defensive', 'Discount Stores'),
    'CSCO': ('Technology', 'Communication Equipment'),
    'CAT': ('Industrials', 'Agricultural - Machinery'),
    'CVX': ('Energy', 'Oil & Gas Integrated'),
    'NFLX': ('Communication Services', 'Entertainment'),
    'ABBV': ('Healthcare', 'Drug Manufacturers - General'),
    'UNH': ('Healthcare', 'Medical - Healthcare Plans'),
    'KO': ('Consumer Defensive', 'Beverages - Non-Alcoholic'),
    'LRCX': ('Technology', 'Semiconductors'),
    'PG': ('Consumer Defensive', 'Household & Personal Products'),
    'AMAT': ('Technology', 'Semiconductors'),
    'PLTR': ('Technology', 'Software - Infrastructure'),
    'HD': ('Consumer Cyclical', 'Home Improvement'),
    'MRK': ('Healthcare', 'Drug Manufacturers - General'),
    'TXN': ('Technology', 'Semiconductors'),
    'GEV': ('Utilities', 'Renewable Utilities'),
    'KLAC': ('Technology', 'Semiconductors'),
    'QCOM': ('Technology', 'Semiconductors'),
    'IBM': ('Technology', 'Information Technology Services'),
    'TMUS': ('Communication Services', 'Telecommunications Services'),
    'ADI': ('Technology', 'Semiconductors'),
    'PEP': ('Consumer Defensive', 'Beverages - Non-Alcoholic'),
    'MCD': ('Consumer Cyclical', 'Restaurants'),
    'SNDK': ('Technology', 'Hardware, Equipment & Parts'),
    'VZ': ('Communication Services', 'Telecommunications Services'),
    'NEE': ('Utilities', 'Regulated Electric'),
    'DIS': ('Communication Services', 'Entertainment'),
    'ANET': ('Technology', 'Computer Hardware'),
    'AMGN': ('Healthcare', 'Drug Manufacturers - General'),
    'CRM': ('Technology', 'Software - Application'),
    'T': ('Communication Services', 'Telecommunications Services'),
    'PANW': ('Technology', 'Software - Infrastructure'),
    'TJX': ('Consumer Cyclical', 'Apparel - Retail'),
    'APP': ('Technology', 'Software - Application'),
    'TMO': ('Healthcare', 'Medical - Diagnostics & Research'),
    'UNP': ('Industrials', 'Railroads'),
    'GILD': ('Healthcare', 'Drug Manufacturers - General'),
    'DELL': ('Technology', 'Computer Hardware'),
    'WDC': ('Technology', 'Computer Hardware'),
    'CRWD': ('Technology', 'Software - Infrastructure'),
    'ISRG': ('Healthcare', 'Medical - Devices'),
    'GLW': ('Technology', 'Hardware, Equipment & Parts'),
    'ABT': ('Healthcare', 'Medical - Devices'),
    'UBER': ('Technology', 'Software - Application'),
    'DE': ('Industrials', 'Agricultural - Machinery'),
    'COP': ('Energy', 'Oil & Gas Exploration & Production'),
    'APH': ('Technology', 'Hardware, Equipment & Parts'),
    'MRVL': ('Technology', 'Semiconductors'),
    'PFE': ('Healthcare', 'Drug Manufacturers - General'),
    'SCCO': ('Basic Materials', 'Copper'),
    'HON': ('Industrials', 'Conglomerates'),
    'VRT': ('Industrials', 'Electrical Equipment & Parts'),
    'CVS': ('Healthcare', 'Medical - Healthcare Plans'),
    'LOW': ('Consumer Cyclical', 'Home Improvement'),
    'SBUX': ('Consumer Cyclical', 'Restaurants'),
    'BKNG': ('Consumer Cyclical', 'Travel Services'),
    'SYK': ('Healthcare', 'Medical - Devices'),
    'NEM': ('Basic Materials', 'Gold'),
    'BMY': ('Healthcare', 'Drug Manufacturers - General'),
    'DHR': ('Healthcare', 'Medical - Diagnostics & Research'),
    'INTU': ('Technology', 'Software - Application'),
    'VRTX': ('Healthcare', 'Biotechnology'),
    'PWR': ('Industrials', 'Engineering & Construction'),
    'PH': ('Industrials', 'Industrial - Machinery'),
    'NOW': ('Technology', 'Software - Application'),
    'SO': ('Utilities', 'Regulated Electric'),
    'ADBE': ('Technology', 'Software - Application'),
    'DUK': ('Utilities', 'Regulated Electric'),
    'SNPS': ('Technology', 'Software - Infrastructure'),
    'CDNS': ('Technology', 'Software - Application'),
    'WMB': ('Energy', 'Oil & Gas Midstream'),
    'MAR': ('Consumer Cyclical', 'Travel Lodging'),
    'HCA': ('Healthcare', 'Medical - Care Facilities'),
    'CMI': ('Industrials', 'Industrial - Machinery'),
    'MCK': ('Healthcare', 'Medical - Distribution'),
    'FTNT': ('Technology', 'Software - Infrastructure'),
    'WM': ('Industrials', 'Waste Management'),
    'ADP': ('Industrials', 'Staffing & Employment Services'),
    'CMCSA': ('Communication Services', 'Telecommunications Services'),
    'FDX': ('Industrials', 'Integrated Freight & Logistics'),
    'FCX': ('Basic Materials', 'Copper'),
    'MNST': ('Consumer Defensive', 'Beverages - Non-Alcoholic'),
    'CSX': ('Industrials', 'Railroads'),
    'ELV': ('Healthcare', 'Medical - Healthcare Plans'),
    'SLB': ('Energy', 'Oil & Gas Equipment & Services'),
    'EPD': ('Energy', 'Oil & Gas Midstream'),
    'BSX': ('Healthcare', 'Medical - Devices'),
    'CEG': ('Utilities', 'Renewable Utilities'),
    'UPS': ('Industrials', 'Integrated Freight & Logistics'),
    'ABNB': ('Consumer Cyclical', 'Travel Services'),
    'MMM': ('Industrials', 'Conglomerates'),
    'MDLZ': ('Consumer Defensive', 'Food Confectioners'),
    'VLO': ('Energy', 'Oil & Gas Refining & Marketing'),
    'EOG': ('Energy', 'Oil & Gas Exploration & Production'),
    'ORLY': ('Consumer Cyclical', 'Specialty Retail'),
    'CI': ('Healthcare', 'Medical - Healthcare Plans'),
    'MPC': ('Energy', 'Oil & Gas Refining & Marketing'),
    'KMI': ('Energy', 'Oil & Gas Midstream'),
    'SHW': ('Basic Materials', 'Chemicals - Specialty'),
    'DDOG': ('Technology', 'Software - Application'),
    'CIEN': ('Technology', 'Communication Equipment'),
    'EMR': ('Industrials', 'Industrial - Machinery'),
    'MPWR': ('Technology', 'Semiconductors'),
    'HLT': ('Consumer Cyclical', 'Travel Lodging'),
    'PSX': ('Energy', 'Oil & Gas Refining & Marketing'),
    'CL': ('Consumer Defensive', 'Household & Personal Products'),
    'NSC': ('Industrials', 'Railroads'),
    'ITW': ('Industrials', 'Industrial - Machinery'),
    'CVNA': ('Consumer Cyclical', 'Auto - Dealerships'),
    'NET': ('Technology', 'Software - Infrastructure'),
    'DASH': ('Communication Services', 'Internet Content & Information'),
    'ECL': ('Basic Materials', 'Chemicals - Specialty'),
    'CTAS': ('Industrials', 'Specialty Business Services'),
    'ET': ('Energy', 'Oil & Gas Midstream'),
    'AEP': ('Utilities', 'Regulated Electric'),
    'LITE': ('Technology', 'Communication Equipment'),
    'ROST': ('Consumer Cyclical', 'Apparel - Retail'),
    'MSI': ('Technology', 'Communication Equipment'),
    'WBD': ('Communication Services', 'Entertainment'),
    'RCL': ('Consumer Cyclical', 'Travel Services'),
    'RSG': ('Industrials', 'Waste Management'),
    'GM': ('Consumer Cyclical', 'Auto - Manufacturers'),
    'BKR': ('Energy', 'Oil & Gas Equipment & Services'),
    'APD': ('Basic Materials', 'Chemicals - Specialty'),
    'FIX': ('Industrials', 'Engineering & Construction'),
    'REGN': ('Healthcare', 'Biotechnology'),
    'CBRS': ('Technology', 'Semiconductors'),
    'NKE': ('Consumer Cyclical', 'Apparel - Footwear & Accessories'),
    'BE': ('Industrials', 'Electrical Equipment & Parts'),
    'D': ('Utilities', 'Regulated Electric'),
    'OXY': ('Energy', 'Oil & Gas Exploration & Production'),
    'URI': ('Industrials', 'Rental & Leasing Services'),
    'OKE': ('Energy', 'Oil & Gas Midstream'),
    'SRE': ('Utilities', 'Diversified Utilities'),
    'TRGP': ('Energy', 'Oil & Gas Midstream'),
    'PCAR': ('Industrials', 'Industrial - Machinery'),
    'KEYS': ('Technology', 'Hardware, Equipment & Parts'),
    'FANG': ('Energy', 'Oil & Gas Exploration & Production'),
    'COHR': ('Technology', 'Hardware, Equipment & Parts'),
    'SNOW': ('Technology', 'Software - Application'),
    'CRWV': ('Technology', 'Software - Infrastructure'),
    'MPLX': ('Energy', 'Oil & Gas Midstream'),
    'TGT': ('Consumer Defensive', 'Discount Stores'),
    'AZO': ('Consumer Cyclical', 'Specialty Retail'),
    'CTVA': ('Basic Materials', 'Agricultural Inputs'),
    'CARR': ('Industrials', 'Industrial - Machinery'),
    'LNG': ('Energy', 'Oil & Gas Midstream'),
    'AME': ('Industrials', 'Electrical Equipment & Parts'),
    'NUE': ('Basic Materials', 'Steel'),
    'BDX': ('Healthcare', 'Medical - Instruments & Supplies'),
    'ADSK': ('Technology', 'Software - Application'),
    'F': ('Consumer Cyclical', 'Auto - Manufacturers'),
    'COR': ('Healthcare', 'Medical - Distribution'),
    'EBAY': ('Consumer Cyclical', 'Specialty Retail'),
    'FAST': ('Industrials', 'Industrial - Distribution'),
    'EA': ('Communication Services', 'Electronic Gaming & Multimedia'),
    'TER': ('Technology', 'Semiconductors'),
    'MCHP': ('Technology', 'Semiconductors'),
    'ETR': ('Utilities', 'Regulated Electric'),
    'MSTR': ('Technology', 'Software - Application'),
    'XEL': ('Utilities', 'Regulated Electric'),
    'ROK': ('Industrials', 'Industrial - Machinery'),
    'EW': ('Healthcare', 'Medical - Devices'),
    'CAH': ('Healthcare', 'Medical - Distribution'),
    'DAL': ('Industrials', 'Airlines, Airports & Air Services'),
    'VST': ('Utilities', 'Independent Power Producers'),
    'EXC': ('Utilities', 'Regulated Electric'),
    'TTWO': ('Communication Services', 'Electronic Gaming & Multimedia'),
    'WAB': ('Industrials', 'Railroads'),
    'HPE': ('Technology', 'Computer Hardware'),
    'CMG': ('Consumer Cyclical', 'Restaurants'),
    'IDXX': ('Healthcare', 'Medical - Diagnostics & Research'),
    'ON': ('Technology', 'Semiconductors'),
    'ODFL': ('Industrials', 'Trucking'),
    'KR': ('Consumer Defensive', 'Grocery Stores'),
    'XYZ': ('Technology', 'Software - Infrastructure'),
    'YUM': ('Consumer Cyclical', 'Restaurants'),
    'KDP': ('Consumer Defensive', 'Beverages - Non-Alcoholic'),
    'SATS': ('Technology', 'Communication Equipment'),
    'ED': ('Utilities', 'Regulated Electric'),
    'EME': ('Industrials', 'Engineering & Construction'),
    'ADM': ('Consumer Defensive', 'Agricultural Farm Products'),
    'DHI': ('Consumer Cyclical', 'Residential Construction'),
    'LYV': ('Communication Services', 'Entertainment'),
    'HSY': ('Consumer Defensive', 'Food Confectioners'),
    'PEG': ('Utilities', 'Regulated Electric'),
    'ALNY': ('Healthcare', 'Biotechnology'),
    'GFS': ('Technology', 'Semiconductors'),
    'ALAB': ('Technology', 'Semiconductors'),
    'HUM': ('Healthcare', 'Medical - Healthcare Plans'),
    'EQT': ('Energy', 'Oil & Gas Exploration & Production'),
    'HAL': ('Energy', 'Oil & Gas Equipment & Services'),
    'JBL': ('Technology', 'Hardware, Equipment & Parts'),
    'WEC': ('Utilities', 'Regulated Electric'),
    'ASTS': ('Technology', 'Communication Equipment'),
    'PPLC': ('Utilities', 'Regulated Electric'),
    'SYY': ('Consumer Defensive', 'Food Distribution'),
    'PCG': ('Utilities', 'Regulated Electric'),
    'VG': ('Energy', 'Oil & Gas Midstream'),
    'VMC': ('Basic Materials', 'Construction Materials'),
    'CCL': ('Consumer Cyclical', 'Leisure'),
    'WDAY': ('Technology', 'Software - Application'),
    'PAYX': ('Industrials', 'Staffing & Employment Services'),
    'RBLX': ('Technology', 'Electronic Gaming & Multimedia'),
    'ROP': ('Technology', 'Software - Application'),
    'MLM': ('Basic Materials', 'Construction Materials'),
    'KVUE': ('Consumer Defensive', 'Household & Personal Products'),
    'STLD': ('Basic Materials', 'Steel'),
    'ZTS': ('Healthcare', 'Drug Manufacturers - General'),
    'CPRT': ('Industrials', 'Specialty Business Services'),
    'KMB': ('Consumer Defensive', 'Household & Personal Products'),
    'CASY': ('Consumer Cyclical', 'Specialty Retail'),
    'A': ('Healthcare', 'Medical - Diagnostics & Research'),
    'ONC': ('Healthcare', 'Medical - Pharmaceuticals'),
    'Q': ('Technology', 'Semiconductors'),
    'DVN': ('Energy', 'Oil & Gas Exploration & Production'),
    'RVMD': ('Healthcare', 'Biotechnology'),
    'RDDT': ('Communication Services', 'Internet Content & Information'),
    'MTZ': ('Industrials', 'Engineering & Construction'),
    'MDLN': ('Healthcare', 'Medical - Instruments & Supplies'),
    'FISV': ('Technology', 'Information Technology Services'),
    'SYM': ('Industrials', 'Industrial - Machinery'),
    'UAL': ('Industrials', 'Airlines, Airports & Air Services'),
    'TWLO': ('Technology', 'Software - Infrastructure'),
    'ATO': ('Utilities', 'Regulated Gas'),
    'AEE': ('Utilities', 'Regulated Electric'),
    'RMD': ('Healthcare', 'Medical - Devices'),
    'DTE': ('Utilities', 'Regulated Electric'),
    'STRC': ('Technology', 'Software - Application'),
    'ZM': ('Technology', 'Software - Application'),
    'EL': ('Consumer Defensive', 'Household & Personal Products'),
    'FOXA': ('Communication Services', 'Entertainment'),
    'IQV': ('Healthcare', 'Medical - Diagnostics & Research'),
    'CRDO': ('Technology', 'Communication Equipment'),
    'CNC': ('Healthcare', 'Medical - Healthcare Plans'),
    'DOV': ('Industrials', 'Industrial - Machinery'),
    'BIIB': ('Healthcare', 'Drug Manufacturers - General'),
    'ZS': ('Technology', 'Software - Infrastructure'),
    'GEHC': ('Healthcare', 'Medical - Healthcare Information Services'),
    'DOW': ('Basic Materials', 'Chemicals'),
    'VRSN': ('Technology', 'Software - Infrastructure'),
    'KHC': ('Consumer Defensive', 'Packaged Foods'),
    'NTRA': ('Healthcare', 'Medical - Diagnostics & Research'),
    'FICO': ('Technology', 'Software - Application'),
    'IR': ('Industrials', 'Industrial - Machinery'),
    'OTIS': ('Industrials', 'Industrial - Machinery'),
    'CNP': ('Utilities', 'Diversified Utilities'),
    'MTSI': ('Technology', 'Semiconductors'),
    'VEEV': ('Healthcare', 'Medical - Healthcare Information Services'),
    'MDB': ('Technology', 'Software - Infrastructure'),
    'TPR': ('Consumer Cyclical', 'Luxury Goods'),
    'NRG': ('Utilities', 'Independent Power Producers'),
    'EIX': ('Utilities', 'Regulated Electric'),
    'ROL': ('Consumer Cyclical', 'Personal Products & Services'),
    'PPL': ('Utilities', 'Regulated Electric'),
    'FOX': ('Communication Services', 'Entertainment'),
    'XYL': ('Industrials', 'Industrial - Machinery'),
    'FE': ('Utilities', 'Regulated Electric'),
    'ES': ('Utilities', 'Regulated Electric'),
    'P': ('Industrials', 'Industrial - Machinery'),
    'EXPE': ('Consumer Cyclical', 'Travel Services'),
    'DXCM': ('Healthcare', 'Medical - Devices'),
    'FSLR': ('Energy', 'Solar'),
    'HUBB': ('Industrials', 'Electrical Equipment & Parts'),
    'JBHT': ('Industrials', 'Integrated Freight & Logistics'),
    'AWK': ('Utilities', 'Regulated Water'),
    'CTSH': ('Technology', 'Information Technology Services'),
    'BG': ('Consumer Defensive', 'Agricultural Farm Products'),
    'UTHR': ('Healthcare', 'Biotechnology'),
    'LYB': ('Basic Materials', 'Chemicals'),
    'NTAP': ('Technology', 'Computer Hardware'),
    'TSN': ('Consumer Defensive', 'Agricultural Farm Products'),
    'FTAI': ('Industrials', 'Rental & Leasing Services'),
    'STRL': ('Industrials', 'Engineering & Construction'),
    'EXE': ('Energy', 'Oil & Gas Exploration & Production'),
    'XPO': ('Industrials', 'Integrated Freight & Logistics'),
    'DG': ('Consumer Defensive', 'Discount Stores'),
    'INSM': ('Healthcare', 'Biotechnology'),
    'PPG': ('Basic Materials', 'Chemicals - Specialty'),
    'CHD': ('Consumer Defensive', 'Household & Personal Products'),
    'FWONK': ('Communication Services', 'Entertainment'),
    'CPAY': ('Technology', 'Software - Infrastructure'),
    'VRSK': ('Technology', 'Software - Services'),
    'FIS': ('Technology', 'Information Technology Services'),
    'RPRX': ('Healthcare', 'Biotechnology'),
    'NI': ('Utilities', 'Regulated Gas'),
    'CMS': ('Utilities', 'Regulated Electric'),
    'DRI': ('Consumer Cyclical', 'Restaurants'),
    'AKAM': ('Technology', 'Software - Infrastructure'),
    'MTD': ('Healthcare', 'Medical - Diagnostics & Research'),
    'WAT': ('Healthcare', 'Medical - Diagnostics & Research'),
    'AFRM': ('Technology', 'Software - Infrastructure'),
    'WST': ('Healthcare', 'Medical - Instruments & Supplies'),
    'FFIV': ('Technology', 'Software - Infrastructure'),
    'ILMN': ('Healthcare', 'Medical - Diagnostics & Research'),
    'VLTO': ('Industrials', 'Industrial - Pollution & Treatment Controls'),
    'PHM': ('Consumer Cyclical', 'Residential Construction'),
    'LEN': ('Consumer Cyclical', 'Residential Construction'),
    'DGX': ('Healthcare', 'Medical - Diagnostics & Research'),
    'ULTA': ('Consumer Cyclical', 'Specialty Retail'),
    'LH': ('Healthcare', 'Medical - Diagnostics & Research'),
    'OMC': ('Communication Services', 'Advertising Agencies'),
    'ALB': ('Basic Materials', 'Chemicals - Specialty'),
    'EXPD': ('Industrials', 'Integrated Freight & Logistics'),
    'ATI': ('Industrials', 'Manufacturing - Metal Fabrication'),
    'CRS': ('Industrials', 'Manufacturing - Metal Fabrication'),
    'CHRW': ('Industrials', 'Integrated Freight & Logistics'),
    'MKSI': ('Technology', 'Hardware, Equipment & Parts'),
    'NXT': ('Technology', 'Consumer Electronics'),
    'DD': ('Basic Materials', 'Chemicals - Specialty'),
    'ULS': ('Industrials', 'Specialty Business Services'),
    'WSM': ('Consumer Cyclical', 'Specialty Retail'),
    'EFX': ('Industrials', 'Consulting Services'),
    'RL': ('Consumer Cyclical', 'Apparel - Manufacturers'),
    'ENTG': ('Technology', 'Semiconductors'),
    'CF': ('Basic Materials', 'Agricultural Inputs'),
    'VTRS': ('Healthcare', 'Drug Manufacturers - Specialty & Generic'),
    'HPQ': ('Technology', 'Computer Hardware'),
    'RBA': ('Industrials', 'Specialty Business Services'),
    'SITM': ('Technology', 'Semiconductors'),
    'MRNA': ('Healthcare', 'Biotechnology'),
    'INCY': ('Healthcare', 'Biotechnology'),
    'EVRG': ('Utilities', 'Regulated Electric'),
    'IFF': ('Basic Materials', 'Chemicals - Specialty'),
    'PKG': ('Consumer Cyclical', 'Packaging & Containers'),
    'LUV': ('Industrials', 'Airlines, Airports & Air Services'),
    'LNT': ('Utilities', 'Regulated Electric'),
    'WES': ('Energy', 'Oil & Gas Midstream'),
    'SMCI': ('Technology', 'Computer Hardware'),
    'IONQ': ('Technology', 'Computer Hardware'),
    'RS': ('Basic Materials', 'Steel'),
    'SNX': ('Technology', 'Technology Distributors'),
    'ROKU': ('Communication Services', 'Entertainment'),
    'APG': ('Industrials', 'Engineering & Construction'),
    'BURL': ('Consumer Cyclical', 'Apparel - Retail'),
    'USFD': ('Consumer Defensive', 'Food Distribution'),
    'WMG': ('Communication Services', 'Entertainment'),
    'FTV': ('Industrials', 'Industrial - Machinery'),
    'GIS': ('Consumer Defensive', 'Packaged Foods'),
    'DLTR': ('Consumer Defensive', 'Discount Stores'),
    'VNOM': ('Energy', 'Oil & Gas Midstream'),
    'IOT': ('Technology', 'Software - Infrastructure'),
    'DKS': ('Consumer Cyclical', 'Specialty Retail'),
    'LII': ('Industrials', 'Construction'),
    'ITT': ('Industrials', 'Industrial - Machinery'),
    'RBC': ('Industrials', 'Manufacturing - Tools & Accessories'),
    'BR': ('Technology', 'Information Technology Services'),
    'CHTR': ('Communication Services', 'Telecommunications Services'),
    'WCC': ('Industrials', 'Industrial - Distribution'),
    'LSCC': ('Technology', 'Semiconductors'),
    'OVV': ('Energy', 'Oil & Gas Exploration & Production'),
    'RIVN': ('Consumer Cyclical', 'Auto - Manufacturers'),
    'PTC': ('Technology', 'Software - Application'),
    'TSCO': ('Consumer Cyclical', 'Specialty Retail'),
    'THC': ('Healthcare', 'Medical - Care Facilities'),
    'NWS': ('Communication Services', 'Entertainment'),
    'AA': ('Basic Materials', 'Aluminum'),
    'TTMI': ('Technology', 'Hardware, Equipment & Parts'),
    'WY': ('Basic Materials', 'Paper, Lumber & Forest Products'),
    'ZBH': ('Healthcare', 'Medical - Devices'),
    'AMKR': ('Technology', 'Semiconductors'),
    'PAA': ('Energy', 'Oil & Gas Midstream'),
    'SSNC': ('Technology', 'Software - Application'),
    'H': ('Consumer Cyclical', 'Travel Lodging'),
    'IP': ('Consumer Cyclical', 'Packaging & Containers'),
    'CLH': ('Industrials', 'Waste Management'),
    'WSO': ('Industrials', 'Industrial - Distribution'),
    'NBIX': ('Healthcare', 'Biotechnology'),
    'RGLD': ('Basic Materials', 'Gold'),
    'LDOS': ('Technology', 'Information Technology Services'),
    'IEX': ('Industrials', 'Industrial - Machinery'),
    'NDSN': ('Industrials', 'Industrial - Machinery'),
    'DOCN': ('Technology', 'Software - Infrastructure'),
    'DTM': ('Energy', 'Oil & Gas Midstream'),
    'PFGC': ('Consumer Defensive', 'Food Distribution'),
    'SN': ('Consumer Cyclical', 'Furnishings, Fixtures & Appliances'),
    'MLI': ('Industrials', 'Manufacturing - Metal Fabrication'),
    'PR': ('Energy', 'Oil & Gas Exploration & Production'),
    'GNRC': ('Industrials', 'Industrial - Machinery'),
    'BALL': ('Consumer Cyclical', 'Packaging & Containers'),
    'TLN': ('Utilities', 'Independent Power Producers'),
    'NWSA': ('Communication Services', 'Entertainment'),
    'GEN': ('Technology', 'Software - Infrastructure'),
    'OKTA': ('Technology', 'Software - Infrastructure'),
    'TKO': ('Communication Services', 'Entertainment'),
    'LECO': ('Industrials', 'Manufacturing - Tools & Accessories'),
    'APA': ('Energy', 'Oil & Gas Exploration & Production'),
    'ARMK': ('Industrials', 'Specialty Business Services'),
    'AAOI': ('Technology', 'Semiconductors'),
    'COKE': ('Consumer Defensive', 'Beverages - Non-Alcoholic'),
    'TYL': ('Technology', 'Software - Application'),
    'CSL': ('Industrials', 'Construction'),
    'DECK': ('Consumer Cyclical', 'Apparel - Footwear & Accessories'),
    'J': ('Industrials', 'Engineering & Construction'),
    'RMBS': ('Technology', 'Semiconductors'),
    'CDW': ('Technology', 'Information Technology Services'),
    'HAS': ('Consumer Cyclical', 'Leisure'),
    'PINS': ('Communication Services', 'Internet Content & Information'),
    'TRU': ('Industrials', 'Consulting Services'),
    'MAS': ('Consumer Cyclical', 'Furnishings, Fixtures & Appliances'),
    'SOLV': ('Healthcare', 'Medical - Care Facilities'),
    'RBRK': ('Technology', 'Software - Infrastructure'),
    'TOST': ('Technology', 'Software - Infrastructure'),
    'SGI': ('Consumer Defensive', 'Household & Personal Products'),
    'SOLS': ('Basic Materials', 'Chemicals - Specialty'),
    'MOD': ('Consumer Cyclical', 'Auto - Parts'),
    'GPC': ('Consumer Cyclical', 'Specialty Retail'),
    'PEN': ('Healthcare', 'Medical - Devices'),
    'TRMB': ('Technology', 'Hardware, Equipment & Parts'),
    'DVA': ('Healthcare', 'Medical - Care Facilities'),
    'BBIO': ('Healthcare', 'Biotechnology'),
    'GH': ('Healthcare', 'Medical - Diagnostics & Research'),
    'BWA': ('Consumer Cyclical', 'Auto - Parts'),
    'DINO': ('Energy', 'Oil & Gas Refining & Marketing'),
    'ONTO': ('Technology', 'Semiconductors'),
    'GGG': ('Industrials', 'Industrial - Machinery'),
    'DY': ('Industrials', 'Engineering & Construction'),
    'NTNX': ('Technology', 'Software - Infrastructure'),
    'MKC': ('Consumer Defensive', 'Packaged Foods'),
    'RRX': ('Industrials', 'Industrial - Machinery'),
    'EXEL': ('Healthcare', 'Biotechnology'),
    'RPM': ('Basic Materials', 'Chemicals - Specialty'),
    'SMMT': ('Healthcare', 'Biotechnology'),
    'NYT': ('Communication Services', 'Publishing'),
    'BJ': ('Consumer Defensive', 'Discount Stores'),
    'ZBRA': ('Technology', 'Communication Equipment'),
    'SMTC': ('Technology', 'Semiconductors'),
    'SAIA': ('Industrials', 'Trucking'),
    'QXO': ('Industrials', 'Industrial - Distribution'),
    'BBY': ('Consumer Cyclical', 'Specialty Retail'),
    'GDDY': ('Technology', 'Software - Infrastructure'),
    'PNW': ('Utilities', 'Regulated Electric'),
    'FIVE': ('Consumer Defensive', 'Discount Stores'),
    'SANM': ('Technology', 'Hardware, Equipment & Parts'),
    'MDGL': ('Healthcare', 'Biotechnology'),
    'TOL': ('Consumer Cyclical', 'Residential Construction'),
    'MEDP': ('Healthcare', 'Medical - Diagnostics & Research'),
    'AVY': ('Consumer Cyclical', 'Packaging & Containers'),
    'IONS': ('Healthcare', 'Biotechnology'),
    'COO': ('Healthcare', 'Medical - Instruments & Supplies'),
    'AR': ('Energy', 'Oil & Gas Exploration & Production'),
    'DT': ('Technology', 'Software - Application'),
    'FIG': ('Technology', 'Software - Application'),
    'AEIS': ('Industrials', 'Electrical Equipment & Parts'),
    'SWK': ('Industrials', 'Manufacturing - Tools & Accessories'),
    'WLK': ('Basic Materials', 'Chemicals - Specialty'),
    'AXSM': ('Healthcare', 'Biotechnology'),
    'U': ('Technology', 'Software - Application'),
    'GWRE': ('Technology', 'Software - Application'),
    'TXRH': ('Consumer Cyclical', 'Restaurants'),
    'VIAV': ('Technology', 'Communication Equipment'),
    'HL': ('Basic Materials', 'Silver'),
    'BLD': ('Industrials', 'Engineering & Construction'),
    'CDE': ('Basic Materials', 'Gold'),
    'ALGN': ('Healthcare', 'Medical - Devices'),
    'KNX': ('Industrials', 'Trucking'),
    'VICR': ('Technology', 'Hardware, Equipment & Parts'),
    'CLX': ('Consumer Defensive', 'Household & Personal Products'),
    'HRL': ('Consumer Defensive', 'Packaged Foods'),
    'APLD': ('Technology', 'Information Technology Services'),
    'SJM': ('Consumer Defensive', 'Packaged Foods'),
    'LFUS': ('Technology', 'Hardware, Equipment & Parts'),
    'AAON': ('Industrials', 'Construction'),
    'BTSG': ('Healthcare', 'Medical - Healthcare Information Services'),
    'SCI': ('Consumer Cyclical', 'Personal Products & Services'),
    'CCK': ('Consumer Cyclical', 'Packaging & Containers'),
    'HUBS': ('Technology', 'Software - Application'),
    'RVTY': ('Healthcare', 'Medical - Diagnostics & Research'),
    'GMED': ('Healthcare', 'Medical - Devices'),
    'ARW': ('Technology', 'Technology Distributors'),
    'UHS': ('Healthcare', 'Medical - Care Facilities'),
    'AM': ('Energy', 'Oil & Gas Midstream'),
    'SWKS': ('Technology', 'Semiconductors'),
    'WTRG': ('Utilities', 'Regulated Water'),
    'PODD': ('Healthcare', 'Medical - Devices'),
    'FPS': ('Industrials', 'Electrical Equipment & Parts'),
    'WMS': ('Industrials', 'Construction'),
    'EHC': ('Healthcare', 'Medical - Care Facilities'),
    'GSAT': ('Communication Services', 'Telecommunications Services'),
    'PAG': ('Consumer Cyclical', 'Auto - Dealerships'),
    'TTD': ('Communication Services', 'Advertising Agencies'),
    'MUSA': ('Consumer Cyclical', 'Specialty Retail'),
    'ARWR': ('Healthcare', 'Biotechnology'),
    'IT': ('Industrials', 'Consulting Services'),
    'AES': ('Utilities', 'Independent Power Producers'),
    'ENSG': ('Healthcare', 'Medical - Care Facilities'),
    'CGNX': ('Technology', 'Hardware, Equipment & Parts'),
    'DPZ': ('Consumer Cyclical', 'Restaurants'),
    'OKLO': ('Utilities', 'Regulated Electric'),
    'JOBY': ('Industrials', 'Airlines, Airports & Air Services'),
    'SFD': ('Consumer Defensive', 'Agricultural Farm Products'),
    'MP': ('Basic Materials', 'Industrial Materials'),
    'LGN': ('Industrials', 'Engineering & Construction'),
    'WTS': ('Industrials', 'Industrial - Machinery'),
    'SPXC': ('Industrials', 'Industrial - Machinery'),
    'RRC': ('Energy', 'Oil & Gas Exploration & Production'),
    'ELAN': ('Healthcare', 'Drug Manufacturers - Specialty & Generic'),
    'GTLS': ('Industrials', 'Industrial - Machinery'),
    'JKHY': ('Technology', 'Information Technology Services'),
    'DAR': ('Consumer Defensive', 'Packaged Foods'),
    'CR': ('Industrials', 'Industrial - Machinery'),
    'GME': ('Consumer Cyclical', 'Specialty Retail'),
    'OGE': ('Utilities', 'Regulated Electric'),
    'BSY': ('Technology', 'Software - Application'),
    'POWL': ('Industrials', 'Electrical Equipment & Parts'),
    'ESI': ('Basic Materials', 'Chemicals - Specialty'),
    'VSAT': ('Technology', 'Communication Equipment'),
    'SUN': ('Energy', 'Oil & Gas Refining & Marketing'),
    'CART': ('Consumer Cyclical', 'Specialty Retail'),
    'MOH': ('Healthcare', 'Medical - Healthcare Plans'),
    'BMRN': ('Healthcare', 'Biotechnology'),
    'DCI': ('Industrials', 'Industrial - Machinery'),
    'DOCU': ('Technology', 'Software - Application'),
    'ALSN': ('Consumer Cyclical', 'Auto - Parts'),
    'MASI': ('Healthcare', 'Medical - Devices'),
    'CYTK': ('Healthcare', 'Biotechnology'),
    'CAVA': ('Consumer Cyclical', 'Restaurants'),
    'AGX': ('Industrials', 'Engineering & Construction'),
    'ACM': ('Industrials', 'Engineering & Construction'),
    'BAX': ('Healthcare', 'Medical - Instruments & Supplies'),
    'FORM': ('Technology', 'Semiconductors'),
    'BROS': ('Consumer Cyclical', 'Restaurants'),
    'LLYVK': ('Communication Services', 'Entertainment'),
    'ZG': ('Communication Services', 'Internet Content & Information'),
    'OC': ('Industrials', 'Construction'),
    'BAH': ('Industrials', 'Consulting Services'),
    'R': ('Industrials', 'Rental & Leasing Services'),
    'CHWY': ('Consumer Cyclical', 'Specialty Retail'),
    'Z': ('Communication Services', 'Internet Content & Information'),
    'SIRI': ('Communication Services', 'Entertainment'),
    'TTC': ('Industrials', 'Manufacturing - Tools & Accessories'),
    'CNM': ('Industrials', 'Industrial - Distribution'),
    'NE': ('Energy', 'Oil & Gas Drilling'),
    'KRYS': ('Healthcare', 'Biotechnology'),
    'AYI': ('Industrials', 'Electrical Equipment & Parts'),
    'PRMB': ('Consumer Defensive', 'Beverages - Non-Alcoholic'),
    'MSGS': ('Communication Services', 'Entertainment'),
    'FLS': ('Industrials', 'Industrial - Machinery'),
    'CHRD': ('Energy', 'Oil & Gas Exploration & Production'),
    'HESM': ('Energy', 'Oil & Gas Midstream'),
    'MTCH': ('Communication Services', 'Internet Content & Information'),
    'GKOS': ('Healthcare', 'Medical - Devices'),
    'ACI': ('Consumer Defensive', 'Grocery Stores'),
    'SFM': ('Consumer Defensive', 'Grocery Stores'),
    'QRVO': ('Technology', 'Semiconductors'),
    'HSIC': ('Healthcare', 'Medical - Distribution'),
    'SAIL': ('Technology', 'Software - Infrastructure'),
    'ENS': ('Industrials', 'Electrical Equipment & Parts'),
    'LEVI': ('Consumer Cyclical', 'Apparel - Manufacturers'),
    'FROG': ('Technology', 'Software - Application'),
    'AGCO': ('Industrials', 'Agricultural - Machinery'),
    'CRUS': ('Technology', 'Semiconductors'),
    'AAL': ('Industrials', 'Airlines, Airports & Air Services'),
    'EMN': ('Basic Materials', 'Chemicals'),
    'MANH': ('Technology', 'Software - Application'),
    'ZWS': ('Industrials', 'Industrial - Pollution & Treatment Controls'),
    'WFRD': ('Energy', 'Oil & Gas Equipment & Services'),
    'HALO': ('Healthcare', 'Biotechnology'),
    'ORA': ('Utilities', 'Renewable Utilities'),
    'AOS': ('Industrials', 'Industrial - Machinery'),
    'NFG': ('Energy', 'Oil & Gas Integrated'),
    'FRVO': ('Utilities', 'Regulated Electric'),
    'KEX': ('Industrials', 'Marine Shipping'),
    'TKR': ('Industrials', 'Manufacturing - Tools & Accessories'),
    'MXL': ('Technology', 'Semiconductors'),
    'W': ('Consumer Cyclical', 'Specialty Retail'),
    'IDA': ('Utilities', 'Regulated Electric'),
    'CMC': ('Basic Materials', 'Steel'),
    'ALGM': ('Technology', 'Semiconductors'),
    'BIO': ('Healthcare', 'Medical - Devices'),
    'TEM': ('Healthcare', 'Medical - Healthcare Information Services'),
    'OSK': ('Industrials', 'Industrial - Machinery'),
    'NOV': ('Energy', 'Oil & Gas Equipment & Services'),
    'PAYC': ('Technology', 'Software - Application'),
    'ECG': ('Industrials', 'Engineering & Construction'),
    'GAP': ('Consumer Cyclical', 'Apparel - Retail'),
    'ESE': ('Technology', 'Hardware, Equipment & Parts'),
    'MTDR': ('Energy', 'Oil & Gas Exploration & Production'),
    'BLDR': ('Industrials', 'Construction'),
    'CELH': ('Consumer Defensive', 'Beverages - Non-Alcoholic'),
    'CORZ': ('Technology', 'Software - Infrastructure'),
    'CWEN': ('Utilities', 'Renewable Utilities'),
    'UGI': ('Utilities', 'Regulated Gas'),
    'LTH': ('Consumer Cyclical', 'Leisure'),
    'ATR': ('Healthcare', 'Medical - Instruments & Supplies'),
    'NUVL': ('Healthcare', 'Biotechnology'),
    'CWAN': ('Technology', 'Software - Application'),
    'PCOR': ('Technology', 'Software - Application'),
    'CRL': ('Healthcare', 'Medical - Diagnostics & Research'),
    'SLAB': ('Technology', 'Semiconductors'),
    'DBX': ('Technology', 'Software - Infrastructure'),
    'TTEK': ('Industrials', 'Engineering & Construction'),
    'HQY': ('Healthcare', 'Medical - Healthcare Information Services'),
    'MYRG': ('Industrials', 'Engineering & Construction'),
    'NCLH': ('Consumer Cyclical', 'Travel Services'),
    'PCVX': ('Healthcare', 'Biotechnology'),
    'TECH': ('Healthcare', 'Biotechnology'),
    'ST': ('Technology', 'Hardware, Equipment & Parts'),
    'PLXS': ('Technology', 'Hardware, Equipment & Parts'),
    'FSS': ('Industrials', 'Industrial - Pollution & Treatment Controls'),
    'AVT': ('Technology', 'Technology Distributors'),
    'IDCC': ('Technology', 'Software - Application'),
    'MOS': ('Basic Materials', 'Agricultural Inputs'),
    'PRAX': ('Healthcare', 'Biotechnology'),
    'AROC': ('Energy', 'Oil & Gas Equipment & Services'),
    'PPC': ('Consumer Defensive', 'Packaged Foods'),
    'AWI': ('Industrials', 'Construction'),
    'ACLX': ('Healthcare', 'Biotechnology'),
    'KGS': ('Energy', 'Oil & Gas Equipment & Services'),
    'DOX': ('Technology', 'Software - Infrastructure'),
    'POOL': ('Industrials', 'Industrial - Distribution'),
    'VFC': ('Consumer Cyclical', 'Apparel - Manufacturers'),
    'JBTM': ('Industrials', 'Industrial - Machinery'),
    'CAG': ('Consumer Defensive', 'Packaged Foods'),
    'TXNM': ('Utilities', 'Regulated Electric'),
    'OSCR': ('Healthcare', 'Medical - Healthcare Plans'),
    'KYMR': ('Healthcare', 'Biotechnology'),
    'ENPH': ('Energy', 'Solar'),
    'LEA': ('Consumer Cyclical', 'Auto - Parts'),
    'MIDD': ('Industrials', 'Industrial - Machinery'),
    'BRKR': ('Healthcare', 'Medical - Devices'),
    'ROAD': ('Industrials', 'Engineering & Construction'),
    'NPO': ('Industrials', 'Industrial - Machinery'),
    'PTGX': ('Healthcare', 'Biotechnology'),
    'CELC': ('Healthcare', 'Biotechnology'),
    'SWX': ('Utilities', 'Regulated Gas'),
    'INGR': ('Consumer Defensive', 'Packaged Foods'),
    'SSRM': ('Basic Materials', 'Gold'),
    'AUGO': ('Basic Materials', 'Other Precious Metals'),
    'LKQ': ('Consumer Cyclical', 'Auto - Parts'),
    'URBN': ('Consumer Cyclical', 'Apparel - Retail'),
    'FLR': ('Industrials', 'Engineering & Construction'),
    'EXP': ('Basic Materials', 'Construction Materials'),
    'GTES': ('Industrials', 'Industrial - Machinery'),
    'CE': ('Basic Materials', 'Chemicals'),
    'AN': ('Consumer Cyclical', 'Auto - Dealerships'),
    'VSNT': ('Industrials', 'Advertising Agencies'),
    'CLF': ('Basic Materials', 'Steel'),
    'LSTR': ('Industrials', 'Integrated Freight & Logistics'),
    'CPB': ('Consumer Defensive', 'Packaged Foods'),
    'LNTH': ('Healthcare', 'Drug Manufacturers - Specialty & Generic'),
    'PCTY': ('Technology', 'Software - Application'),
    'TGTX': ('Healthcare', 'Biotechnology'),
    'LAD': ('Consumer Cyclical', 'Auto - Dealerships'),
    'LW': ('Consumer Defensive', 'Packaged Foods'),
    'EQPT': ('Industrials', 'Rental & Leasing Services'),
    'GVA': ('Industrials', 'Engineering & Construction'),
    'NXST': ('Communication Services', 'Entertainment'),
    'INGM': ('Technology', 'Information Technology Services'),
    'TTAN': ('Technology', 'Software - Application'),
    'YOU': ('Technology', 'Software - Application'),
    'RYTM': ('Healthcare', 'Biotechnology'),
    'CORT': ('Healthcare', 'Biotechnology'),
    'AXTA': ('Basic Materials', 'Chemicals - Specialty'),
    'MHK': ('Consumer Cyclical', 'Furnishings, Fixtures & Appliances'),
    'PRIM': ('Industrials', 'Engineering & Construction'),
    'RGEN': ('Healthcare', 'Medical - Instruments & Supplies'),
    'S': ('Technology', 'Software - Infrastructure'),
    'WH': ('Consumer Cyclical', 'Travel Lodging'),
    'MSM': ('Industrials', 'Industrial - Distribution'),
    'PTCT': ('Healthcare', 'Biotechnology'),
    'NJR': ('Utilities', 'Regulated Gas'),
    'IBP': ('Consumer Cyclical', 'Residential Construction'),
    'MUR': ('Energy', 'Oil & Gas Exploration & Production'),
    'TFX': ('Healthcare', 'Medical - Instruments & Supplies'),
    'PATH': ('Technology', 'Software - Infrastructure'),
    'PEGA': ('Technology', 'Software - Application'),
    'SRRK': ('Healthcare', 'Biotechnology'),
    'EAT': ('Consumer Cyclical', 'Restaurants'),
    'SNDR': ('Industrials', 'Trucking'),
    'APPF': ('Technology', 'Software - Application'),
    'BKH': ('Utilities', 'Diversified Utilities'),
    'POR': ('Utilities', 'Regulated Electric'),
    'ETSY': ('Consumer Cyclical', 'Specialty Retail'),
    'ESTC': ('Technology', 'Software - Application'),
    'MATX': ('Industrials', 'Marine Shipping'),
    'LB': ('Energy', 'Oil & Gas Equipment & Services'),
    'CGON': ('Healthcare', 'Biotechnology'),
    'CRC': ('Energy', 'Oil & Gas Exploration & Production'),
    'MGY': ('Energy', 'Oil & Gas Exploration & Production'),
    'RGTI': ('Technology', 'Computer Hardware'),
    'CWST': ('Industrials', 'Waste Management'),
    'PSN': ('Industrials', 'Industrial - Machinery'),
    'PRM': ('Basic Materials', 'Chemicals - Specialty'),
    'CENX': ('Basic Materials', 'Aluminum'),
    'GXO': ('Industrials', 'Integrated Freight & Logistics'),
    'IMVT': ('Healthcare', 'Biotechnology'),
    'LBRT': ('Energy', 'Oil & Gas Equipment & Services'),
    'NOVT': ('Technology', 'Hardware, Equipment & Parts'),
    'ESAB': ('Industrials', 'Manufacturing - Metal Fabrication'),
    'COGT': ('Healthcare', 'Biotechnology'),
    'RUSHA': ('Consumer Cyclical', 'Auto - Dealerships'),
    'BEPC': ('Utilities', 'Renewable Utilities'),
    'DUOL': ('Technology', 'Software - Application'),
    'KMX': ('Consumer Cyclical', 'Auto - Dealerships'),
    'APLS': ('Healthcare', 'Biotechnology'),
    'EPAM': ('Technology', 'Information Technology Services'),
    'TMHC': ('Consumer Cyclical', 'Residential Construction'),
    'OGS': ('Utilities', 'Regulated Gas'),
    'DLB': ('Technology', 'Information Technology Services'),
    'SEI': ('Energy', 'Oil & Gas Equipment & Services'),
    'CNX': ('Energy', 'Oil & Gas Exploration & Production'),
    'CAR': ('Industrials', 'Rental & Leasing Services'),
    'SR': ('Utilities', 'Regulated Gas'),
    'SITE': ('Industrials', 'Industrial - Distribution'),
    'LYFT': ('Technology', 'Software - Application'),
    'LQDA': ('Healthcare', 'Biotechnology'),
    'GOLF': ('Consumer Cyclical', 'Leisure'),
    'VSH': ('Technology', 'Semiconductors'),
    'LEGN': ('Healthcare', 'Biotechnology'),
    'PBF': ('Energy', 'Oil & Gas Refining & Marketing'),
    'BC': ('Consumer Cyclical', 'Auto - Recreational Vehicles'),
    'OLLI': ('Consumer Defensive', 'Discount Stores'),
    'SPHR': ('Communication Services', 'Entertainment'),
    'WEX': ('Technology', 'Software - Infrastructure'),
    'PAGP': ('Energy', 'Oil & Gas Midstream'),
    'LPX': ('Basic Materials', 'Paper, Lumber & Forest Products'),
    'AXTI': ('Technology', 'Semiconductors'),
    'HRB': ('Consumer Cyclical', 'Personal Products & Services'),
    'BIPC': ('Utilities', 'Regulated Gas'),
    'HIMS': ('Healthcare', 'Medical - Equipment & Services'),
    'M': ('Consumer Cyclical', 'Department Stores'),
    'PTEN': ('Energy', 'Oil & Gas Drilling'),
    'APGE': ('Healthcare', 'Biotechnology'),
    'FND': ('Consumer Cyclical', 'Home Improvement'),
    'UNF': ('Industrials', 'Specialty Business Services'),
    'CHH': ('Consumer Cyclical', 'Travel Lodging'),
    'SXT': ('Basic Materials', 'Chemicals - Specialty'),
    'GNTX': ('Consumer Cyclical', 'Auto - Parts'),
    'CROX': ('Consumer Cyclical', 'Apparel - Footwear & Accessories'),
    'ZETA': ('Technology', 'Software - Application'),
    'MIRM': ('Healthcare', 'Biotechnology'),
    'TERN': ('Healthcare', 'Biotechnology'),
    'LBRDA': ('Communication Services', 'Telecommunications Services'),
    'MDU': ('Industrials', 'Conglomerates'),
    'SON': ('Consumer Cyclical', 'Packaging & Containers'),
    'FCN': ('Industrials', 'Consulting Services'),
    'LAUR': ('Consumer Defensive', 'Education & Training Services'),
    'SYNA': ('Technology', 'Semiconductors'),
    'IRDM': ('Communication Services', 'Telecommunications Services'),
    'UFPI': ('Basic Materials', 'Paper, Lumber & Forest Products'),
    'INDV': ('Healthcare', 'Drug Manufacturers - Specialty & Generic'),
    'NTSK': ('Technology', 'Software - Services'),
    'REYN': ('Consumer Cyclical', 'Packaging & Containers'),
    'COCO': ('Consumer Defensive', 'Beverages - Non-Alcoholic'),
    'HCC': ('Energy', 'Coal'),
    'POST': ('Consumer Defensive', 'Packaged Foods'),
    'RELY': ('Technology', 'Software - Infrastructure'),
    'IPGP': ('Technology', 'Semiconductors'),
    'ACLS': ('Technology', 'Semiconductors'),
    'HRI': ('Industrials', 'Rental & Leasing Services'),
    'FTDR': ('Consumer Cyclical', 'Personal Products & Services'),
    'DAN': ('Consumer Cyclical', 'Auto - Parts'),
    'CRGY': ('Energy', 'Oil & Gas Exploration & Production'),
    'EXLS': ('Technology', 'Information Technology Services'),
    'XMTR': ('Industrials', 'Industrial - Machinery'),
    'MIR': ('Industrials', 'Industrial - Machinery'),
    'TDS': ('Communication Services', 'Telecommunications Services'),
    'NWE': ('Utilities', 'Diversified Utilities'),
    'SHC': ('Healthcare', 'Medical - Diagnostics & Research'),
    'KVYO': ('Technology', 'Software - Infrastructure'),
    'CVLT': ('Technology', 'Software - Application'),
    'DIOD': ('Technology', 'Semiconductors'),
    'ACIW': ('Technology', 'Software - Infrastructure'),
    'WSC': ('Industrials', 'Rental & Leasing Services'),
    'MAT': ('Consumer Cyclical', 'Leisure'),
    'NAVN': ('Technology', 'Software - Application'),
    'BCO': ('Industrials', 'Security & Protection Services'),
    'CRK': ('Energy', 'Oil & Gas Exploration & Production'),
    'PLNT': ('Consumer Cyclical', 'Leisure'),
    'BOOT': ('Consumer Cyclical', 'Apparel - Retail'),
    'REZI': ('Industrials', 'Security & Protection Services'),
    'LOPE': ('Consumer Defensive', 'Education & Training Services'),
    'CAI': ('Healthcare', 'Biotechnology'),
    'RDNT': ('Healthcare', 'Medical - Diagnostics & Research'),
    'TEX': ('Industrials', 'Agricultural - Machinery'),
    'PI': ('Technology', 'Semiconductors'),
    'TDW': ('Energy', 'Oil & Gas Equipment & Services'),
    'VVV': ('Energy', 'Oil & Gas Refining & Marketing'),
    'GTLB': ('Technology', 'Software - Application'),
    'HNGE': ('Healthcare', 'Medical - Healthcare Information Services'),
    'SYRE': ('Healthcare', 'Biotechnology'),
    'CBT': ('Basic Materials', 'Chemicals - Specialty'),
    'KNF': ('Basic Materials', 'Construction Materials'),
    'CNR': ('Energy', 'Coal'),
    'INSW': ('Energy', 'Oil & Gas Midstream'),
    'MTRN': ('Basic Materials', 'Industrial Materials'),
    'ANDG': ('Consumer Cyclical', 'Specialty Business Services'),
    'MANE': ('Healthcare', 'Biotechnology'),
    'ACMR': ('Technology', 'Semiconductors'),
    'WHD': ('Energy', 'Oil & Gas Equipment & Services'),
    'OLED': ('Technology', 'Hardware, Equipment & Parts'),
    'ALK': ('Industrials', 'Airlines, Airports & Air Services'),
    'HP': ('Energy', 'Oil & Gas Drilling'),
    'SAIC': ('Technology', 'Information Technology Services'),
    'ATMU': ('Industrials', 'Industrial - Pollution & Treatment Controls'),
    'ALH': ('Consumer Cyclical', 'Furnishings, Fixtures & Appliances'),
    'MTH': ('Consumer Cyclical', 'Residential Construction'),
    'KBR': ('Industrials', 'Engineering & Construction'),
    'BDC': ('Technology', 'Communication Equipment'),
    'MWA': ('Industrials', 'Industrial - Machinery'),
    'FBIN': ('Industrials', 'Construction'),
    'TPH': ('Consumer Cyclical', 'Residential Construction'),
    'LASR': ('Technology', 'Semiconductors'),
    'TVTX': ('Healthcare', 'Biotechnology'),
    'TPC': ('Industrials', 'Engineering & Construction'),
    'BRC': ('Industrials', 'Security & Protection Services'),
    'TREX': ('Industrials', 'Construction'),
    'SLGN': ('Consumer Cyclical', 'Packaging & Containers'),
    'BLLN': ('Healthcare', 'Medical - Diagnostics & Research'),
    'VNT': ('Technology', 'Hardware, Equipment & Parts'),
    'TNL': ('Consumer Cyclical', 'Travel Services'),
    'THO': ('Consumer Cyclical', 'Auto - Recreational Vehicles'),
    'FOUR': ('Technology', 'Software - Infrastructure'),
    'OII': ('Energy', 'Oil & Gas Equipment & Services'),
    'BILL': ('Technology', 'Software - Application'),
    'CPRX': ('Healthcare', 'Biotechnology'),
    'LRN': ('Consumer Defensive', 'Education & Training Services'),
    'SM': ('Energy', 'Oil & Gas Exploration & Production'),
    'AMRX': ('Healthcare', 'Drug Manufacturers - Specialty & Generic'),
    'GFF': ('Industrials', 'Conglomerates'),
    'MMSI': ('Healthcare', 'Medical - Instruments & Supplies'),
    'POWI': ('Technology', 'Semiconductors'),
    'NVST': ('Healthcare', 'Medical - Equipment & Services'),
    'KNTK': ('Energy', 'Oil & Gas Midstream'),
    'OPLN': ('Consumer Cyclical', 'Auto - Dealerships'),
    'OTTR': ('Utilities', 'Diversified Utilities'),
    'DOCS': ('Healthcare', 'Medical - Healthcare Information Services'),
    'PVH': ('Consumer Cyclical', 'Apparel - Manufacturers'),
    'CALM': ('Consumer Defensive', 'Agricultural Farm Products'),
    'SKY': ('Consumer Cyclical', 'Residential Construction'),
    'CRNX': ('Healthcare', 'Biotechnology'),
    'IRTC': ('Healthcare', 'Medical - Devices'),
    'LION': ('Communication Services', 'Entertainment'),
    'PII': ('Consumer Cyclical', 'Auto - Recreational Vehicles'),
    'FLNC': ('Utilities', 'Renewable Utilities'),
    'BFAM': ('Consumer Cyclical', 'Personal Products & Services'),
    'ITRI': ('Technology', 'Hardware, Equipment & Parts'),
    'RNG': ('Technology', 'Software - Application'),
    'BOX': ('Technology', 'Software - Application'),
    'VSCO': ('Consumer Cyclical', 'Apparel - Retail'),
    'WAY': ('Technology', 'Information Technology Services'),
    'KTB': ('Consumer Cyclical', 'Apparel - Manufacturers'),
    'ACAD': ('Healthcare', 'Biotechnology'),
    'OGN': ('Healthcare', 'Drug Manufacturers - General'),
    'WRBY': ('Healthcare', 'Medical - Instruments & Supplies'),
    'WING': ('Consumer Cyclical', 'Restaurants'),
    'DNTH': ('Healthcare', 'Biotechnology'),
    'GPGI': ('Industrials', 'Manufacturing - Metal Fabrication'),
    'UCTT': ('Technology', 'Semiconductors'),
    'CVI': ('Energy', 'Oil & Gas Refining & Marketing'),
    'BMI': ('Technology', 'Hardware, Equipment & Parts'),
    'AMBA': ('Technology', 'Semiconductors'),
    'QLYS': ('Technology', 'Software - Infrastructure'),
    'CC': ('Basic Materials', 'Chemicals - Specialty'),
    'OSIS': ('Technology', 'Hardware, Equipment & Parts'),
    'EWTX': ('Healthcare', 'Biotechnology'),
    'KFY': ('Industrials', 'Staffing & Employment Services'),
    'AVA': ('Utilities', 'Diversified Utilities'),
    'VECO': ('Technology', 'Semiconductors'),
    'VRNS': ('Technology', 'Software - Infrastructure'),
    'ALHC': ('Healthcare', 'Medical - Healthcare Plans'),
    'SMG': ('Basic Materials', 'Agricultural Inputs'),
    'CON': ('Healthcare', 'Medical - Equipment & Services'),
    'PPTA': ('Basic Materials', 'Other Precious Metals'),
    'VKTX': ('Healthcare', 'Biotechnology'),
    'VCYT': ('Healthcare', 'Biotechnology'),
    'YSS': ('Technology', 'Communication Equipment'),
    'NATL': ('Technology', 'Software - Application'),
    'FIZZ': ('Consumer Defensive', 'Beverages - Non-Alcoholic'),
    'ABG': ('Consumer Cyclical', 'Auto - Dealerships'),
    'LEU': ('Energy', 'Uranium'),
    'BELFB': ('Technology', 'Hardware, Equipment & Parts'),
    'ARLP': ('Energy', 'Coal'),
    'MSGE': ('Communication Services', 'Entertainment'),
    'BBWI': ('Consumer Cyclical', 'Specialty Retail'),
    'CHEF': ('Consumer Defensive', 'Food Distribution'),
    'SKYW': ('Industrials', 'Airlines, Airports & Air Services'),
    'ELF': ('Consumer Defensive', 'Household & Personal Products'),
    'ANF': ('Consumer Cyclical', 'Apparel - Retail'),
    'BATRK': ('Communication Services', 'Entertainment'),
    'ASO': ('Consumer Cyclical', 'Specialty Retail'),
    'RUN': ('Energy', 'Solar'),
    'YETI': ('Consumer Cyclical', 'Leisure'),
    'LIF': ('Technology', 'Software - Application'),
    'ERAS': ('Healthcare', 'Biotechnology'),
    'HYMC': ('Basic Materials', 'Gold'),
    'FUL': ('Basic Materials', 'Chemicals - Specialty'),
    'BKD': ('Healthcare', 'Medical - Care Facilities'),
    'EXTR': ('Technology', 'Communication Equipment'),
    'RXO': ('Industrials', 'Trucking'),
    'BKV': ('Energy', 'Oil & Gas Exploration & Production'),
    'MMS': ('Industrials', 'Specialty Business Services'),
    'CNK': ('Communication Services', 'Entertainment'),
    'SMR': ('Utilities', 'Renewable Utilities'),
    'TWST': ('Healthcare', 'Medical - Diagnostics & Research'),
    'MZTI': ('Consumer Defensive', 'Packaged Foods'),
    'UNFI': ('Consumer Defensive', 'Food Distribution'),
    'INOD': ('Technology', 'Information Technology Services'),
    'OPCH': ('Healthcare', 'Medical - Care Facilities'),
    'TDC': ('Technology', 'Software - Infrastructure'),
    'OLN': ('Basic Materials', 'Chemicals - Specialty'),
    'AVNT': ('Basic Materials', 'Chemicals - Specialty'),
    'ICUI': ('Healthcare', 'Medical - Instruments & Supplies'),
    'PAY': ('Technology', 'Information Technology Services'),
    'SUNC': ('Energy', 'Oil & Gas Midstream'),
    'ITGR': ('Healthcare', 'Medical - Devices'),
    'AAP': ('Consumer Cyclical', 'Specialty Retail'),
    'GEO': ('Industrials', 'Security & Protection Services'),
    'IAC': ('Technology', 'Internet Content & Information'),
    'COLM': ('Consumer Cyclical', 'Apparel - Manufacturers'),
    'CTRI': ('Utilities', 'Regulated Gas'),
    'ADEA': ('Technology', 'Software - Application'),
    'BSM': ('Energy', 'Oil & Gas Exploration & Production'),
    'PRVA': ('Healthcare', 'Medical - Healthcare Information Services'),
    'PATK': ('Consumer Cyclical', 'Furnishings, Fixtures & Appliances'),
    'BHE': ('Technology', 'Hardware, Equipment & Parts'),
    'CAKE': ('Consumer Cyclical', 'Restaurants'),
    'KN': ('Technology', 'Communication Equipment'),
    'HAYW': ('Industrials', 'Electrical Equipment & Parts'),
    'PARR': ('Energy', 'Oil & Gas Refining & Marketing'),
    'NN': ('Communication Services', 'Internet Content & Information'),
    'QTWO': ('Technology', 'Software - Application'),
    'DNLI': ('Healthcare', 'Biotechnology'),
    'BTU': ('Energy', 'Coal'),
    'VC': ('Consumer Cyclical', 'Auto - Parts'),
    'WOLF': ('Technology', 'Semiconductors'),
    'KBH': ('Consumer Cyclical', 'Residential Construction'),
    'CECO': ('Industrials', 'Industrial - Pollution & Treatment Controls'),
    'SHOO': ('Consumer Cyclical', 'Apparel - Footwear & Accessories'),
    'CLMT': ('Energy', 'Oil & Gas Exploration & Production'),
    'SUPN': ('Healthcare', 'Drug Manufacturers - Specialty & Generic'),
    'PLAB': ('Technology', 'Semiconductors'),
    'WK': ('Technology', 'Software - Application'),
    'NTCT': ('Technology', 'Software - Infrastructure'),
    'DK': ('Energy', 'Oil & Gas Refining & Marketing'),
    'EXPO': ('Industrials', 'Consulting Services'),
    'CARG': ('Consumer Cyclical', 'Auto - Dealerships'),
    'SLNO': ('Healthcare', 'Biotechnology'),
    'BEAM': ('Healthcare', 'Biotechnology'),
    'MGEE': ('Utilities', 'Diversified Utilities'),
    'GRBK': ('Consumer Cyclical', 'Residential Construction'),
    'NSIT': ('Technology', 'Technology Distributors'),
    'ARCB': ('Industrials', 'Trucking'),
    'DYN': ('Healthcare', 'Biotechnology'),
    'PTRN': ('Technology', 'Software - Application'),
    'TRN': ('Industrials', 'Railroads'),
    'TXG': ('Healthcare', 'Medical - Healthcare Information Services'),
    'TALO': ('Energy', 'Oil & Gas Exploration & Production'),
    'TARS': ('Healthcare', 'Biotechnology'),
    'CALY': ('Consumer Cyclical', 'Leisure'),
    'RHI': ('Industrials', 'Staffing & Employment Services'),
    'HAE': ('Healthcare', 'Medical - Instruments & Supplies'),
    'KMT': ('Industrials', 'Manufacturing - Tools & Accessories'),
    'AYA': ('Basic Materials', 'Other Precious Metals'),
    'KD': ('Technology', 'Information Technology Services'),
    'AEHR': ('Technology', 'Semiconductors'),
    'EEFT': ('Technology', 'Software - Infrastructure'),
    'FA': ('Industrials', 'Specialty Business Services'),
    'UNIT': ('Communication Services', 'Telecommunications Services'),
    'NESR': ('Energy', 'Oil & Gas Equipment & Services'),
    'NOG': ('Energy', 'Oil & Gas Exploration & Production'),
    'FSLY': ('Technology', 'Software - Application'),
    'GRAL': ('Healthcare', 'Medical - Diagnostics & Research'),
    'ALMS': ('Healthcare', 'Biotechnology'),
    'ASH': ('Basic Materials', 'Chemicals - Specialty'),
    'NP': ('Technology', 'Software - Application'),
    'CALX': ('Technology', 'Software - Application'),
    'HOG': ('Consumer Cyclical', 'Auto - Recreational Vehicles'),
    'CWT': ('Utilities', 'Regulated Water'),
    'FLOC': ('Energy', 'Oil & Gas Equipment & Services'),
    'WHR': ('Consumer Cyclical', 'Furnishings, Fixtures & Appliances'),
    'IRON': ('Healthcare', 'Biotechnology'),
    'HLIO': ('Industrials', 'Industrial - Machinery'),
    'TENB': ('Technology', 'Software - Infrastructure'),
    'ANAB': ('Healthcare', 'Biotechnology'),
    'KLRA': ('Healthcare', 'Biotechnology'),
    'VISN': ('Technology', 'Communication Equipment'),
    'ATKR': ('Industrials', 'Electrical Equipment & Parts'),
    'SAH': ('Consumer Cyclical', 'Auto - Dealerships'),
    'ARQT': ('Healthcare', 'Biotechnology'),
    'IDYA': ('Healthcare', 'Biotechnology'),
    'MNR': ('Energy', 'Oil & Gas Exploration & Production'),
    'AEO': ('Consumer Cyclical', 'Apparel - Retail'),
    'BKE': ('Consumer Cyclical', 'Apparel - Retail'),
    'VERA': ('Healthcare', 'Biotechnology'),
    'BRZE': ('Technology', 'Software - Application'),
    'GRND': ('Technology', 'Software - Application'),
    'AESI': ('Energy', 'Oil & Gas Equipment & Services'),
    'HUN': ('Basic Materials', 'Chemicals'),
    'ELVN': ('Healthcare', 'Biotechnology'),
    'SHAK': ('Consumer Cyclical', 'Restaurants'),
    'PENG': ('Technology', 'Hardware, Equipment & Parts'),
    'TNGX': ('Healthcare', 'Biotechnology'),
    'DBD': ('Technology', 'Software - Application'),
    'ROG': ('Technology', 'Hardware, Equipment & Parts'),
    'AMSC': ('Industrials', 'Industrial - Machinery'),
    'RAMP': ('Technology', 'Software - Infrastructure'),
    'RARE': ('Healthcare', 'Biotechnology'),
    'FRPT': ('Consumer Defensive', 'Packaged Foods'),
    'BCC': ('Basic Materials', 'Construction Materials'),
    'TMDX': ('Healthcare', 'Medical - Devices'),
    'DGII': ('Technology', 'Communication Equipment'),
    'RCUS': ('Healthcare', 'Biotechnology'),
    'ABM': ('Industrials', 'Specialty Business Services'),
    'MH': ('Consumer Defensive', 'Education & Training Services'),
    'DRVN': ('Consumer Cyclical', 'Auto - Dealerships'),
    'ACHC': ('Healthcare', 'Medical - Care Facilities'),
    'PCT': ('Industrials', 'Industrial - Pollution & Treatment Controls'),
    'RLAY': ('Healthcare', 'Biotechnology'),
    'AMR': ('Energy', 'Coal'),
    'ICHR': ('Technology', 'Semiconductors'),
    'HUBG': ('Industrials', 'Integrated Freight & Logistics'),
    'HE': ('Utilities', 'Diversified Utilities'),
    'BW': ('Industrials', 'Industrial - Machinery'),
    'LMAT': ('Healthcare', 'Medical - Instruments & Supplies'),
    'BLBD': ('Consumer Cyclical', 'Auto - Manufacturers'),
    'RH': ('Consumer Cyclical', 'Specialty Retail'),
    'WERN': ('Industrials', 'Trucking'),
    'GRDN': ('Healthcare', 'Medical - Distribution'),
    'AMPX': ('Industrials', 'Electrical Equipment & Parts'),
    'DFTX': ('Healthcare', 'Biotechnology'),
    'AXGN': ('Healthcare', 'Medical - Devices'),
    'PBI': ('Industrials', 'Integrated Freight & Logistics'),
    'WLY': ('Communication Services', 'Publishing'),
    'HTFL': ('Healthcare', 'Medical - Healthcare Information Services'),
    'PUMP': ('Energy', 'Oil & Gas Equipment & Services'),
    'PBH': ('Healthcare', 'Medical - Distribution'),
    'CXT': ('Industrials', 'Industrial - Machinery'),
    'NGL': ('Energy', 'Oil & Gas Midstream'),
    'ORKA': ('Healthcare', 'Biotechnology'),
    'PRDO': ('Consumer Defensive', 'Education & Training Services'),
    'ALRM': ('Technology', 'Software - Application'),
    'UTI': ('Consumer Defensive', 'Education & Training Services'),
    'AVPT': ('Technology', 'Software - Infrastructure'),
    'VERX': ('Technology', 'Software - Application'),
    'TYRA': ('Healthcare', 'Biotechnology'),
    'THR': ('Industrials', 'Industrial - Machinery'),
    'COHU': ('Technology', 'Semiconductors'),
    'INVX': ('Energy', 'Oil & Gas Equipment & Services'),
    'BRUN': (None, None),
    'GPCR': ('Healthcare', 'Biotechnology'),
    'USAR': ('Basic Materials', 'Industrial Materials'),
    'FUN': ('Consumer Cyclical', 'Leisure'),
    'SEM': ('Healthcare', 'Medical - Care Facilities'),
    'WTTR': ('Utilities', 'Regulated Water'),
    'ADPT': ('Healthcare', 'Biotechnology'),
    'VRRM': ('Technology', 'Information Technology Services'),
    'ATEN': ('Technology', 'Software - Infrastructure'),
    'CLDX': ('Healthcare', 'Biotechnology'),
    'GEL': ('Energy', 'Oil & Gas Midstream'),
    'HTO': ('Utilities', 'Regulated Water'),
    'AGYS': ('Technology', 'Software - Application'),
    'INFQ': ('Technology', 'Computer Hardware'),
    'TNET': ('Industrials', 'Staffing & Employment Services'),
    'OMCL': ('Healthcare', 'Medical - Healthcare Information Services'),
    'OUST': ('Technology', 'Hardware, Equipment & Parts'),
    'SPSC': ('Technology', 'Software - Infrastructure'),
    'FLYW': ('Technology', 'Information Technology Services'),
    'ASTH': ('Healthcare', 'Medical - Care Facilities'),
    'FIGS': ('Consumer Cyclical', 'Apparel - Manufacturers'),
    'MGNI': ('Communication Services', 'Advertising Agencies'),
    'TRVI': ('Healthcare', 'Biotechnology'),
    'IMNM': ('Healthcare', 'Biotechnology'),
    'PGNY': ('Healthcare', 'Medical - Healthcare Information Services'),
    'XPRO': ('Energy', 'Oil & Gas Equipment & Services'),
    'SAM': ('Consumer Defensive', 'Beverages - Alcoholic'),
    'MD': ('Healthcare', 'Medical - Care Facilities'),
    'KOD': ('Healthcare', 'Biotechnology'),
    'STRA': ('Consumer Defensive', 'Education & Training Services'),
    'ALG': ('Industrials', 'Agricultural - Machinery'),
    'SGRY': ('Healthcare', 'Medical - Care Facilities'),
    'ALKT': ('Technology', 'Software - Application'),
    'SEMR': ('Technology', 'Software - Application'),
    'STOK': ('Healthcare', 'Biotechnology'),
    'TH': ('Industrials', 'Specialty Business Services'),
    'WLTH': ('Technology', 'Software - Application'),
    'SRPT': ('Healthcare', 'Biotechnology'),
    'BAND': ('Technology', 'Software - Infrastructure'),
    'LPG': ('Energy', 'Oil & Gas Midstream'),
    'SPB': ('Consumer Defensive', 'Household & Personal Products'),
    'VCEL': ('Healthcare', 'Biotechnology'),
    'PLSE': ('Healthcare', 'Medical - Instruments & Supplies'),
    'SION': ('Healthcare', 'Biotechnology'),
    'LKFT': ('Healthcare', 'Biotechnology'),
    'SONO': ('Technology', 'Consumer Electronics'),
    'MLYS': ('Healthcare', 'Biotechnology'),
    'BL': ('Technology', 'Software - Application'),
    'LWLG': ('Basic Materials', 'Chemicals - Specialty'),
    'PDFS': ('Technology', 'Software - Application'),
    'ADUS': ('Healthcare', 'Medical - Care Facilities'),
    'HRMY': ('Healthcare', 'Biotechnology'),
    'SNDX': ('Healthcare', 'Biotechnology'),
    'PRKS': ('Consumer Cyclical', 'Leisure'),
    'FMC': ('Basic Materials', 'Agricultural Inputs'),
    'SKYT': ('Technology', 'Semiconductors'),
    'AGIO': ('Healthcare', 'Biotechnology'),
    'CBZ': ('Industrials', 'Specialty Business Services'),
    'TILE': ('Consumer Cyclical', 'Furnishings, Fixtures & Appliances'),
    'PSUS': (None, None),
    'NCNO': ('Technology', 'Software - Application'),
    'AMRC': ('Industrials', 'Engineering & Construction'),
    'HNI': ('Industrials', 'Business Equipment & Supplies'),
    'CTS': ('Technology', 'Hardware, Equipment & Parts'),
    'FIVN': ('Technology', 'Software - Application'),
    'INVA': ('Healthcare', 'Biotechnology'),
    'INTA': ('Technology', 'Software - Application'),
    'VSTS': ('Industrials', 'Rental & Leasing Services'),
    'STAA': ('Healthcare', 'Medical - Instruments & Supplies'),
    'NVRI': ('Industrials', 'Waste Management'),
    'BKSY': ('Technology', 'Hardware, Equipment & Parts'),
    'ECVT': ('Basic Materials', 'Chemicals - Specialty'),
    'LINC': ('Consumer Defensive', 'Education & Training Services'),
    'APPN': ('Technology', 'Software - Application'),
    'INBX': ('Healthcare', 'Biotechnology'),
    'BOBS': ('Consumer Cyclical', 'Specialty Retail'),
    'WBTN': ('Technology', 'Software - Application'),
    'HLX': ('Energy', 'Oil & Gas Equipment & Services'),
    'AIP': ('Technology', 'Semiconductors'),
    'DNOW': ('Energy', 'Oil & Gas Equipment & Services'),
    'AMBQ': ('Technology', 'Semiconductors'),
    'ZD': ('Communication Services', 'Advertising Agencies'),
    'SOC': ('Energy', 'Oil & Gas Drilling'),
    'DMRA': ('Healthcare', 'Biotechnology'),
    'WKC': ('Energy', 'Oil & Gas Refining & Marketing'),
    'EVTC': ('Technology', 'Software - Infrastructure'),
    'GBX': ('Industrials', 'Railroads'),
    'SLVM': ('Basic Materials', 'Paper, Lumber & Forest Products'),
    'PRCT': ('Healthcare', 'Medical - Devices'),
    'HCSG': ('Healthcare', 'Medical - Care Facilities'),
    'BLKB': ('Technology', 'Software - Application'),
    'CNXC': ('Technology', 'Information Technology Services'),
    'WBI': ('Energy', 'Oil & Gas Energy'),
    'AHCO': ('Healthcare', 'Medical - Devices'),
    'ARDT': ('Healthcare', 'Medical - Care Facilities'),
    'ENOV': ('Healthcare', 'Medical - Devices'),
    'AGL': ('Healthcare', 'Medical - Care Facilities'),
    'KRP': ('Energy', 'Oil & Gas Exploration & Production'),
    'ATRC': ('Healthcare', 'Medical - Instruments & Supplies'),
    'LZB': ('Consumer Cyclical', 'Furnishings, Fixtures & Appliances'),
    'KALV': ('Healthcare', 'Biotechnology'),
    'NTLA': ('Healthcare', 'Biotechnology'),
    'TTI': ('Energy', 'Oil & Gas Equipment & Services'),
    'CCS': ('Consumer Cyclical', 'Residential Construction'),
    'ARLO': ('Industrials', 'Security & Protection Services'),
    'VPG': ('Technology', 'Hardware, Equipment & Parts'),
    'URGN': ('Healthcare', 'Biotechnology'),
    'EYE': ('Consumer Cyclical', 'Specialty Retail'),
    'PAHC': ('Healthcare', 'Drug Manufacturers - Specialty & Generic'),
    'JJSF': ('Consumer Defensive', 'Packaged Foods'),
    'TRS': ('Consumer Cyclical', 'Packaging & Containers'),
    'VRDN': ('Healthcare', 'Biotechnology'),
    'ALGT': ('Industrials', 'Airlines, Airports & Air Services'),
    'DMLP': ('Energy', 'Oil & Gas Exploration & Production'),
    'MAZE': ('Healthcare', 'Biotechnology'),
    'HLIT': ('Technology', 'Communication Equipment'),
    'PRG': ('Industrials', 'Rental & Leasing Services'),
    'WLDN': ('Industrials', 'Engineering & Construction'),
    'NRIX': ('Healthcare', 'Biotechnology'),
    'NKTR': ('Healthcare', 'Biotechnology'),
    'RVLV': ('Consumer Cyclical', 'Specialty Retail'),
    'KSS': ('Consumer Cyclical', 'Department Stores'),
    'CRI': ('Consumer Cyclical', 'Apparel - Retail'),
    'HLF': ('Consumer Defensive', 'Packaged Foods'),
    'MRTN': ('Industrials', 'Trucking'),
    'NSSC': ('Industrials', 'Security & Protection Services'),
    'MAN': ('Industrials', 'Staffing & Employment Services'),
    'FTRE': ('Healthcare', 'Biotechnology'),
    'RAPP': ('Healthcare', 'Biotechnology'),
    'CAPR': ('Healthcare', 'Biotechnology'),
    'NPKI': ('Energy', 'Oil & Gas Equipment & Services'),
    'WGS': ('Healthcare', 'Medical - Healthcare Information Services'),
    'AVBP': ('Healthcare', 'Biotechnology'),
    'WWW': ('Consumer Cyclical', 'Apparel - Footwear & Accessories'),
    'PVLA': ('Healthcare', 'Biotechnology'),
    'PRGS': ('Technology', 'Software - Application'),
    'AEVA': ('Consumer Cyclical', 'Auto - Parts'),
    'GIII': ('Consumer Cyclical', 'Apparel - Manufacturers'),
    'CMP': ('Basic Materials', 'Industrial Materials'),
    'ADTN': ('Technology', 'Communication Equipment'),
    'INSP': ('Healthcare', 'Medical - Devices'),
    'NSP': ('Industrials', 'Staffing & Employment Services'),
    'YELP': ('Communication Services', 'Internet Content & Information'),
    'DEC': ('Energy', 'Oil & Gas Exploration & Production'),
    'IPX': ('Basic Materials', 'Industrial Materials'),
    'DFH': ('Consumer Cyclical', 'Residential Construction'),
    'BV': ('Industrials', 'Specialty Business Services'),
    'GPRE': ('Basic Materials', 'Chemicals - Specialty'),
    'SEPN': ('Healthcare', 'Biotechnology'),
    'GLUE': ('Healthcare', 'Biotechnology'),
    'ICFI': ('Industrials', 'Consulting Services'),
    'AVNS': ('Healthcare', 'Medical - Devices'),
    'VIA': ('Technology', 'Software - Application'),
    'XPEL': ('Consumer Cyclical', 'Auto - Parts'),
    'AORT': ('Healthcare', 'Medical - Devices'),
    'AOSL': ('Technology', 'Semiconductors'),
    'HROW': ('Healthcare', 'Drug Manufacturers - Specialty & Generic'),
    'KMTS': ('Healthcare', 'Medical - Instruments & Supplies'),
    'ENR': ('Industrials', 'Electrical Equipment & Parts'),
    'SBH': ('Consumer Cyclical', 'Specialty Retail'),
    'OLMA': ('Healthcare', 'Biotechnology'),
    'AMN': ('Healthcare', 'Medical - Care Facilities'),
    'AVLN': ('Healthcare', 'Medical - Pharmaceuticals'),
    'XIFR': ('Utilities', 'Independent Power Producers'),
    'CNMD': ('Healthcare', 'Medical - Devices'),
    'IART': ('Healthcare', 'Medical - Devices'),
    'DLX': ('Communication Services', 'Advertising Agencies'),
    'COLL': ('Healthcare', 'Drug Manufacturers - Specialty & Generic'),
    'BLFS': ('Healthcare', 'Medical - Instruments & Supplies'),
    'PZZA': ('Consumer Cyclical', 'Restaurants'),
    'AMLX': ('Healthcare', 'Biotechnology'),
    'SMPL': ('Consumer Defensive', 'Packaged Foods'),
    'GNK': ('Industrials', 'Marine Shipping'),
    'CDNA': ('Healthcare', 'Medical - Diagnostics & Research'),
    'BCAX': ('Healthcare', 'Biotechnology'),
    'ROCK': ('Industrials', 'Construction'),
    'LIND': ('Consumer Cyclical', 'Travel Services'),
    'GHM': ('Industrials', 'Industrial - Machinery'),
    'HTLD': ('Industrials', 'Trucking'),
    'MBX': ('Healthcare', 'Biotechnology'),
    'ATEX': ('Communication Services', 'Telecommunications Services'),
    'CRVS': ('Healthcare', 'Biotechnology'),
    'CEVA': ('Technology', 'Semiconductors'),
    'SCHL': ('Communication Services', 'Publishing'),
    'TBN': ('Energy', 'Oil & Gas Exploration & Production'),
    'UPBD': ('Technology', 'Software - Application'),
    'NNE': ('Industrials', 'Industrial - Machinery'),
    'MLKN': ('Consumer Cyclical', 'Furnishings, Fixtures & Appliances'),
    'LXU': ('Basic Materials', 'Chemicals'),
    'SBGI': ('Communication Services', 'Entertainment'),
    'USPH': ('Healthcare', 'Medical - Care Facilities'),
    'AIAI': ('Industrials', 'Conglomerates'),
    'CRML': ('Basic Materials', 'Industrial Materials'),
    'EYPT': ('Healthcare', 'Biotechnology'),
    'OMDA': ('Healthcare', 'Medical - Healthcare Information Services'),
    'LGIH': ('Consumer Cyclical', 'Residential Construction'),
    'FCEL': ('Industrials', 'Electrical Equipment & Parts'),
    'DAKT': ('Technology', 'Hardware, Equipment & Parts'),
    'THRM': ('Consumer Cyclical', 'Auto - Parts'),
    'TNDM': ('Healthcare', 'Medical - Devices'),
    'WYFI': ('Technology', 'Information Technology Services'),
    'CGEM': ('Healthcare', 'Medical - Pharmaceuticals'),
    'PHAT': ('Healthcare', 'Biotechnology'),
    'LMB': ('Industrials', 'Engineering & Construction'),
    'CODI': ('Industrials', 'Conglomerates'),
    'SDGR': ('Healthcare', 'Medical - Healthcare Information Services'),
    'PSIX': ('Industrials', 'Industrial - Machinery'),
    'BJRI': ('Consumer Cyclical', 'Restaurants'),
    'SHEN': ('Communication Services', 'Telecommunications Services'),
    'ETON': ('Healthcare', 'Biotechnology'),
    'CVLG': ('Industrials', 'Trucking'),
    'PCRX': ('Healthcare', 'Drug Manufacturers - Specialty & Generic'),
    'AVO': ('Consumer Defensive', 'Food Distribution'),
    'HNRG': ('Energy', 'Coal'),
    'CCOI': ('Communication Services', 'Telecommunications Services'),
    'JANX': ('Healthcare', 'Biotechnology'),
    'OMER': ('Healthcare', 'Biotechnology'),
    'SPTX': ('Healthcare', 'Biotechnology'),
    'CD': ('Technology', 'Information Technology Services'),
    'WGO': ('Consumer Cyclical', 'Auto - Recreational Vehicles'),
    'XNCR': ('Healthcare', 'Biotechnology'),
    'LBRX': ('Healthcare', 'Biotechnology'),
    'EFOR': ('Technology', 'Information Technology Services'),
    'MRAM': ('Technology', 'Semiconductors'),
    'CDNL': ('Industrials', 'Industrial - Infrastructure Operations'),
    'NX': ('Industrials', 'Construction'),
    'BBSI': ('Industrials', 'Staffing & Employment Services'),
    'VTS': ('Energy', 'Oil & Gas Exploration & Production'),
    'ANRO': ('Healthcare', 'Biotechnology'),
    'AMPH': ('Healthcare', 'Drug Manufacturers - Specialty & Generic'),
    'ZBIO': ('Healthcare', 'Biotechnology'),
    'METC': ('Energy', 'Coal'),
    'AZTA': ('Healthcare', 'Medical - Instruments & Supplies'),
    'TXO': ('Energy', 'Oil & Gas Exploration & Production'),
    'EPC': ('Consumer Defensive', 'Household & Personal Products'),
    'QDEL': ('Healthcare', 'Medical - Instruments & Supplies'),
    'SNDA': ('Healthcare', 'Medical - Care Facilities'),
    'LYTS': ('Technology', 'Hardware, Equipment & Parts'),
    'HZO': ('Consumer Cyclical', 'Specialty Retail'),
    'BVS': ('Healthcare', 'Medical - Devices'),
    'JBIO': ('Healthcare', 'Biotechnology'),
    'EHAB': ('Healthcare', 'Medical - Care Facilities'),
    'DSP': ('Technology', 'Software - Application'),
    'FOXF': ('Consumer Cyclical', 'Auto - Parts'),
    'HSTM': ('Healthcare', 'Medical - Healthcare Information Services'),
    'CNNE': ('Consumer Cyclical', 'Restaurants'),
    'FWRG': ('Consumer Cyclical', 'Restaurants'),
    'NTGR': ('Technology', 'Communication Equipment'),
    'CYRX': ('Industrials', 'Integrated Freight & Logistics'),
    'DSGN': ('Healthcare', 'Biotechnology'),
    'CBRL': ('Consumer Cyclical', 'Restaurants'),
    'SIBN': ('Healthcare', 'Medical - Devices'),
    'QNST': ('Communication Services', 'Advertising Agencies'),
    'EVER': ('Communication Services', 'Internet Content & Information'),
    'SPIR': ('Industrials', 'Specialty Business Services'),
    'GRPN': ('Communication Services', 'Internet Content & Information'),
    'MITK': ('Technology', 'Software - Application'),
    'CBLL': ('Healthcare', 'Medical - Devices'),
    'MAMA': ('Consumer Defensive', 'Packaged Foods'),
    'TRAX': ('Healthcare', 'Biotechnology'),
    'KRUS': ('Consumer Cyclical', 'Restaurants'),
    'ZVRA': ('Healthcare', 'Biotechnology'),
    'SSTK': ('Communication Services', 'Internet Content & Information'),
    'GMRS': ('Healthcare', 'Medical - Care Facilities'),
    'ORN': ('Industrials', 'Engineering & Construction'),
    'FTK': ('Energy', 'Oil & Gas Equipment & Services'),
    'BZH': ('Consumer Cyclical', 'Residential Construction'),
    'LPTH': ('Technology', 'Hardware, Equipment & Parts'),
    'ASIX': ('Basic Materials', 'Chemicals'),
    'CLFD': ('Technology', 'Communication Equipment'),
    'CSTL': ('Healthcare', 'Medical - Diagnostics & Research'),
    'BIOA': ('Healthcare', 'Biotechnology'),
    'PAR': ('Technology', 'Software - Application'),
    'OXM': ('Consumer Cyclical', 'Apparel - Manufacturers'),
    'SD': ('Energy', 'Oil & Gas Exploration & Production'),
    'SHAZ': ('Technology', 'Information Technology Services'),
    'MEG': ('Industrials', 'Waste Management'),
    'CARS': ('Communication Services', 'Internet Content & Information'),
    'HELE': ('Consumer Defensive', 'Household & Personal Products'),
    'ONT': ('Industrials', 'Environmental Services'),
    'KRT': ('Consumer Cyclical', 'Packaging & Containers'),
    'TCMD': ('Healthcare', 'Medical - Devices'),
    'OOMA': ('Communication Services', 'Telecommunications Services'),
    'RIGL': ('Healthcare', 'Biotechnology'),
    'TECX': ('Healthcare', 'Biotechnology'),
    'AMWD': ('Consumer Cyclical', 'Furnishings, Fixtures & Appliances'),
    'XE': ('Industrials', 'Industrial - Machinery'),
    'CBIO': ('Healthcare', 'Biotechnology'),
    'MEC': ('Industrials', 'Manufacturing - Metal Fabrication'),
    'MBUU': ('Consumer Cyclical', 'Auto - Recreational Vehicles'),
    'ODTX': ('Healthcare', 'Biotechnology'),
}
