"""Generate SYNTHETIC minute/daily data in the exact repo layout.

Purpose: verify plumbing (no-lookahead, fills, walk-forward, selector)
without network access. Synthetic prices are random walks; by
construction there is NO edge in them. Any 'performance' measured on this
data is noise and is labeled as such everywhere it appears.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import numpy as np
import pandas as pd

from src.config import CFG
from src.data.universe_builder import build_daily_panel, save_universe
from src.utils.time_utils import ET

RNG = np.random.default_rng(42)
TICKERS = ["SPY"] + [f"SYN{i:02d}" for i in range(1, 25)]
DATES = pd.bdate_range("2025-04-01", "2025-09-30")

# intraday volume shape (rough U-curve), minutes since 09:30
_MIN = np.arange(390)
_VOL_SHAPE = 1.6 * np.exp(-_MIN / 45) + 0.35 + 1.1 * np.exp(-(389 - _MIN) / 60)
_VOL_SHAPE = _VOL_SHAPE / _VOL_SHAPE.sum()


def _day_minutes(d: pd.Timestamp, prev_close: float, base_daily_vol_shares: float):
    gap = RNG.normal(0, 0.02)
    if RNG.random() < 0.12:
        gap += RNG.choice([-1, 1]) * RNG.uniform(0.03, 0.12)
    o = prev_close * (1 + gap)
    sigma_min = RNG.uniform(0.0006, 0.0035)
    day_mult = float(np.exp(RNG.normal(0, 0.6)))

    rows = []
    # sparse premarket 08:00-09:29 (every ~5 min)
    px = o * (1 + RNG.normal(0, 0.004))
    for m in range(0, 90, 5):
        ts = pd.Timestamp(d.year, d.month, d.day, 8, 0, tz=ET) + pd.Timedelta(minutes=m)
        r = RNG.normal(0, sigma_min * 1.5)
        c = px * (1 + r)
        hi = max(px, c) * (1 + abs(RNG.normal(0, sigma_min)))
        lo = min(px, c) * (1 - abs(RNG.normal(0, sigma_min)))
        v = max(1, int(base_daily_vol_shares * day_mult * 0.0006 * RNG.uniform(0.2, 2)))
        rows.append((ts, px, hi, lo, c, v))
        px = c
    pm_last = px

    # RTH 09:30-15:59, drift mildly linked to gap sign (regime flavor only)
    drift = 0.00002 * np.sign(gap) * RNG.choice([1, 1, -1])
    px = o
    for m in range(390):
        ts = pd.Timestamp(d.year, d.month, d.day, 9, 30, tz=ET) + pd.Timedelta(minutes=m)
        r = RNG.normal(drift, sigma_min)
        c = px * (1 + r)
        hi = max(px, c) * (1 + abs(RNG.normal(0, sigma_min * 0.7)))
        lo = min(px, c) * (1 - abs(RNG.normal(0, sigma_min * 0.7)))
        v = max(1, int(base_daily_vol_shares * day_mult * _VOL_SHAPE[m] * RNG.uniform(0.4, 1.8)))
        rows.append((ts, px, hi, lo, c, v))
        px = c
    df = pd.DataFrame(rows, columns=["ts", "open", "high", "low", "close", "volume"])
    df["transactions"] = (df["volume"] // 17).astype("int64")
    return df, float(px), pm_last


def main() -> None:
    print(f"SYNTHETIC generator: {len(TICKERS)} tickers x {len(DATES)} bdays")
    base_price = {t: float(RNG.uniform(4, 180)) for t in TICKERS}
    base_vol = {t: float(RNG.uniform(0.8e6, 15e6)) for t in TICKERS}
    prev_close = dict(base_price)

    daily_rows = []
    CFG.paths.minute.mkdir(parents=True, exist_ok=True)
    for d in DATES:
        frames = []
        for t in TICKERS:
            mdf, close, _ = _day_minutes(d, prev_close[t], base_vol[t])
            mdf.insert(0, "ticker", t)
            frames.append(mdf)
            rth = mdf[mdf["ts"].dt.time >= pd.Timestamp("09:30").time()]
            daily_rows.append({
                "ticker": t, "date": pd.Timestamp(d.date()),
                "open": float(rth.iloc[0]["open"]), "high": float(rth["high"].max()),
                "low": float(rth["low"].min()), "close": float(rth.iloc[-1]["close"]),
                "volume": float(rth["volume"].sum()),
                "transactions": int(rth["transactions"].sum()),
            })
            prev_close[t] = close
        day = pd.concat(frames, ignore_index=True).sort_values(["ticker", "ts"])
        day.to_parquet(CFG.paths.minute / f"{d:%Y-%m-%d}.parquet", index=False)

    daily = pd.DataFrame(daily_rows)
    CFG.paths.daily.mkdir(parents=True, exist_ok=True)
    for y, g in daily.groupby(daily["date"].dt.year):
        g.sort_values(["date", "ticker"]).to_parquet(
            CFG.paths.daily / f"daily_{y}.parquet", index=False)

    panel = build_daily_panel(daily)
    save_universe(panel)
    (CFG.paths.root / "data" / "SYNTHETIC_DATA_WARNING.md").write_text(
        "# WARNING\n\nEverything under data/ was generated by "
        "scripts/make_synthetic_data.py. It is random-walk SYNTHETIC data "
        "for plumbing verification only. Delete data/processed and "
        "data/universe before loading real Massive files.\n")
    print(f"wrote {len(DATES)} minute files, {daily['date'].nunique()} daily rows/day x {len(TICKERS)} tickers")
    print("panel rows:", len(panel))


if __name__ == "__main__":
    main()
