"""Render a backtest as a single self-contained HTML report."""
from __future__ import annotations

import base64
from datetime import datetime
from io import BytesIO
from pathlib import Path

import pandas as pd
from jinja2 import Template

from halal_gap.backtest.engine import BacktestArtifacts
from halal_gap.backtest.metrics import Metrics
from halal_gap.utils.config import reports_dir


_TEMPLATE = Template(
    """
<!doctype html>
<html><head><meta charset="utf-8"><title>Halal Gap ORB - Stage 1 Backtest</title>
<style>
  body { font-family: -apple-system, sans-serif; margin: 24px; color: #222; }
  h1 { margin-bottom: 4px; }
  .sub { color: #666; margin-bottom: 24px; }
  table { border-collapse: collapse; width: 100%; margin-bottom: 24px; font-size: 13px; }
  th, td { border: 1px solid #ddd; padding: 6px 8px; text-align: right; }
  th { background: #f5f5f5; text-align: left; }
  td:first-child { text-align: left; }
  .metrics td { font-variant-numeric: tabular-nums; }
  .good { color: #0a7; font-weight: 600; }
  .bad { color: #b00; font-weight: 600; }
  img { max-width: 100%; height: auto; }
  .small { font-size: 11px; color: #888; }
</style></head><body>
<h1>Halal Gap ORB &mdash; Stage 1 Backtest</h1>
<div class="sub">Generated {{ generated_at }}</div>

<h2>Headline metrics</h2>
<table class="metrics">
<tr><th>Metric</th><th>Value</th></tr>
{% for k, v in metrics_rows %}
<tr><td>{{ k }}</td><td>{{ v }}</td></tr>
{% endfor %}
</table>

<h2>Equity curve</h2>
{% if equity_png %}<img src="data:image/png;base64,{{ equity_png }}"/>{% else %}<i>No equity data</i>{% endif %}

<h2>Monthly returns heatmap</h2>
{% if monthly_png %}<img src="data:image/png;base64,{{ monthly_png }}"/>{% else %}<i>Insufficient data</i>{% endif %}

<h2>Trades ({{ trade_count }})</h2>
{{ trades_table | safe }}

<h2>Rejected candidates ({{ reject_count }})</h2>
{{ rejects_table | safe }}

<p class="small">Generated by halal_gap.backtest.report. Slippage, frictions per
config/settings.yaml. Long-only, halal-filtered, S&P 500 point-in-time universe.</p>
</body></html>
"""
)


def _fig_to_b64(fig) -> str:  # type: ignore[no-untyped-def]
    buf = BytesIO()
    fig.savefig(buf, format="png", bbox_inches="tight", dpi=110)
    buf.seek(0)
    return base64.b64encode(buf.read()).decode("ascii")


def _plot_equity(equity: pd.DataFrame) -> str:
    if equity.empty:
        return ""
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots(figsize=(8, 3))
    ax.plot(equity["date"], equity["equity"], color="#234")
    ax.set_xlabel("date")
    ax.set_ylabel("equity")
    ax.grid(True, alpha=0.3)
    return _fig_to_b64(fig)


def _plot_monthly(equity: pd.DataFrame) -> str:
    if equity.empty or len(equity) < 5:
        return ""
    import matplotlib.pyplot as plt
    eq = equity.copy()
    eq["date"] = pd.to_datetime(eq["date"])
    eq = eq.set_index("date").sort_index()
    monthly = eq["equity"].resample("ME").last().pct_change().dropna()
    if monthly.empty:
        return ""
    pivot = monthly.to_frame("ret")
    pivot["year"] = pivot.index.year
    pivot["month"] = pivot.index.month
    heat = pivot.pivot(index="year", columns="month", values="ret")
    fig, ax = plt.subplots(figsize=(8, max(2, 0.5 * len(heat))))
    im = ax.imshow(heat.values, cmap="RdYlGn", aspect="auto", vmin=-0.1, vmax=0.1)
    ax.set_xticks(range(heat.shape[1]))
    ax.set_xticklabels(heat.columns)
    ax.set_yticks(range(heat.shape[0]))
    ax.set_yticklabels(heat.index)
    for i in range(heat.shape[0]):
        for j in range(heat.shape[1]):
            v = heat.values[i, j]
            if pd.notna(v):
                ax.text(j, i, f"{v*100:.1f}", ha="center", va="center", fontsize=7, color="#000")
    fig.colorbar(im, ax=ax, shrink=0.6)
    return _fig_to_b64(fig)


def render_report(
    artifacts: BacktestArtifacts,
    metrics: Metrics,
    out_path: Path | None = None,
) -> Path:
    """Render the backtest into an HTML file under reports/."""
    if out_path is None:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        out_path = reports_dir() / f"stage1_backtest_{ts}.html"

    metric_rows = [
        ("Total return", f"{metrics.total_return*100:.2f}%"),
        ("CAGR", f"{metrics.cagr*100:.2f}%"),
        ("Sharpe", f"{metrics.sharpe:.2f}"),
        ("Sortino", f"{metrics.sortino:.2f}"),
        ("Max drawdown", f"{metrics.max_drawdown*100:.2f}%"),
        ("Hit rate", f"{metrics.hit_rate*100:.1f}%"),
        ("Avg win R", f"{metrics.avg_win_r:+.2f}"),
        ("Avg loss R", f"{metrics.avg_loss_r:+.2f}"),
        ("Profit factor", f"{metrics.profit_factor:.2f}"),
        ("Trades", f"{metrics.trades}"),
        ("Trading days", f"{metrics.trading_days}"),
        ("Trades/day", f"{metrics.trades_per_day:.2f}"),
    ]

    trades = artifacts.trades.copy()
    if not trades.empty:
        for col in ("entry_price", "exit_price", "entry_stop", "initial_stop"):
            if col in trades.columns:
                trades[col] = trades[col].astype(float).round(4)
        for col in ("pnl_dollars",):
            if col in trades.columns:
                trades[col] = trades[col].astype(float).round(2)
        for col in ("pnl_r", "high_water_r", "rvol_5min", "premarket_rvol", "gap_pct"):
            if col in trades.columns:
                trades[col] = trades[col].astype(float).round(3)

    trades_html = trades.to_html(index=False) if not trades.empty else "<i>No trades</i>"
    rejects_html = (
        artifacts.candidates.to_html(index=False)
        if not artifacts.candidates.empty
        else "<i>No rejected candidates</i>"
    )

    html = _TEMPLATE.render(
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        metrics_rows=metric_rows,
        equity_png=_plot_equity(artifacts.equity),
        monthly_png=_plot_monthly(artifacts.equity),
        trade_count=len(trades),
        reject_count=len(artifacts.candidates),
        trades_table=trades_html,
        rejects_table=rejects_html,
    )
    out_path.write_text(html, encoding="utf-8")
    return out_path
